CodeStarterCamp_Week2/main.swift
@Journey36 
안녕하세요 글렌!
step2 PR 보냅니다.
**고민되었던 점**
1.  Set -> String
lottoNum 의 값을 Set 으로 받아 왔기 때문에 계속 Set 으로 작업을 하다가 마지막에 print 문을 출력하는 부분에서 [] 를 뺀 String 값이 출력 되어야 하기 때문에 Set -> String 값으로 바꾸는 법을 고민하다가 찾기 못하고 결국 Set -> Array -> String 으로 바꾸는 방식을 선택했습니다.
2. 함수 안에 1기능만 
야곰님이 세션에서 함수당 5줄을 넘기 말라고 말씀해 주셔서 최대한 간결하게 작성하려고 노력했으나... 2가지 함수는 5줄이 넘어버렸는데요.
최대한 함수의 이름에 걸맞는 행동만 할 수 있도록 노력하였습니다.😂
**조언을 구하고 싶은 점** 
1. printMatch 함수를 print 만 해주는 함수 String으로 변환 해주는 함수 2가지로 나누는 것이 좋을까요?
=> Week2 [STEP 2] cherrishRed

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/main.swift, CodeStarterCamp_Week2/step2.swift
@Neph3779  안녕하세요!
Week2 / Step2 PR 발행 합니다.
고민한점 및 질문은 아래와 같습니다.
고민한 점
1. 야곰의 리더세션에서 함수는 5줄 이내 / 함수의 들여쓰기는 한 번만 이용하는것을 권장하였습니다.
그에 따라서 최대한 함수를 쪼개어 위의 권장사항을 지키고자 노력해봤습니다.
2. 저는  컬렉션 타입으로 세트를 이용하고싶었는데, Step2의 내용에서 let myLottoNumbers: [Int] = [~~] 이렇게 할당하게끔 되어있길래, 타입 캐스팅을 통해 Array <-> Set 의 변환을 진행했습니다.
질문 점
DM에 보내드리긴 했지만...
제가 각 스텝마다 브랜치를 나누어서 진행 -> 원격저장소의 main 에 push 하고싶습니다. (결론은 로컬 저장소와 다른 원격 저장소의 브랜치)
이 방법이 가능한것인지? 가능하다면 주로 개발자들이 개발할 때는 어떤식으로 진행하는지 궁금합니다!
실제로 개발 시 로컬 저장소에서 지정한 이름 그대로 원격저장소에 같은 이름의 브랜치를 생성하여 push하고 pr -> merge하는 방식을 많이 사용하는지요...
감사합니다.
=> Week2 [STEP 2] JM.Y

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/Lotto/LottoNumberGenerator.swift, CodeStarterCamp_Week2/Lotto/LottoOptions.swift, CodeStarterCamp_Week2/Lotto/LottoStore.swift, CodeStarterCamp_Week2/main.swift
안녕하세요 네프! @Neph3779
Step2 PR 입니다!
---
- 최대한 순서도를 토대로 코드 작성해보기
- Naming 최대한 의식하면서 작성하기
- 함수 들여쓰기, 쪼개기 신경쓰면서 작성하기
- Array Collection 활용하기
- Set Collection 활용하기
감사합니다!
저녁 맛있게 드세용~!😆
=> Week2 [STEP 2] 마이노

CodeStarterCamp_Week2/main.swift
안녕하세요 글렌 @Journey36 
STEP 3 PR보냅니다 ㅎㅎ
- 로또 당첨 번호 생성 함수를 호출할때마다 회차와 로또 번호를 `Dictionary`에 저장한다고하여 `generateLottoNumbers`함수내 값을 반환하기전에 `saveLottoDrawNumbers`함수로 `lottoDrawHistoryRepository`에 저장해주었습니다. 그런데 호출할때마다와 실행때마다가 헷갈렸던것 같습니다. 실행은 내부에 코드가 있어야할것같고 호출은 외부에서 호출할때마다 값을 저장하는 방식이라고 받아들여지긴하는데요
뭔가 깔끔한 코드를 생각했을때는 `generateLottoNumbers`함수내 메서드를 넣어주는게 적절하다고 판단했습니다.
의도한바가 맞는지? 궁금합니다.
`generateLottoNumbers`함수내 `saveLottoDrawNumbers`함수까지 들어가있으면 `generateLottoNumbers`함수는 두개의 기능을 한다고 봐야하는걸까요 ? 아니면 각각 독립적인 함수의 기능인데 `generateLottoNumbers`함수내에서 호출한걸까요 ?
- 요구사항에 적힌 출력문을 보면 배열의 대괄호가 확인되지않아서 그것을 제거해주는 `description.trimmingCharacters(in: )`함수를 사용했는데요 다른방법도 있는지 궁금합니다.
- 그리고 `lottoDrawHistoryRepository`의 `value`값에 `description.trimmingCharacters(in: )`함수를 적용하면 메서드 적용이되지만 `lottoDrawHistoryRepository`자체의 …
=> Week2 [STEP 3] 쿼카

CodeStarterCamp_Week2/Lotto/LottoOptions.swift, CodeStarterCamp_Week2/Lotto/LottoStore.swift, CodeStarterCamp_Week2/main.swift
안녕하세요 네프! @Neph3779
Step3 PR 입니다!
오늘 눈이 온다네요😱
---
- 네이밍 vs 가독성
- 네이밍이 길어지다보니 가독성이 떨어지는 느낌.
- 하지만 가독성보단 확실한 뜻을 전달해주는게 1순위가 아닐까? 라는 생각으로 간결함은 포기했습니다.
- Dictionary의 활용
- 함수의 오버로딩
- 옵셔널 바인딩
감사합니다!
즐거운 주말 보내세용😆
=> Week2 [STEP 3] 마이노

CodeStarterCamp_Week2/main.swift
@Ldoy  안녕하세요 타코캣님! Step2도 잘 부탁드립니다! 😀
* ```print("My Lotto Numbers : \(myLottoNumbers)")```은 요구 사항에 없었지만, 비교 값이 제대로된 값이 나오는지 확인하기 위해 넣었습니다! 
* ```func printSetToInt()```은 출력값중 **[ ]** 을 제거하고 **,** 을 값 사이에 넣고 Array 값을 Int 값으로 출력하기 위해 만든 함수입니다.
1. 미션의 요구사항 중, Collection Type의 값을 **[]을 제거하고 , 을 값 사이에 넣은 상태* 로 출력해야하는 것
* 우선 **[ ]** 을 제거하기 위해서 Array의 index로 value에 하나하나 접근해서 출력하는 방법을 선택했습니다.
* terminator 값에 **", "** 을 주고보니 마지막 값에 , 가 붙게되어 마지막 값만 따로 접근하였습니다.
* 함수를 짜고 보니 이래저래 조건이 많이 붙고 가독성도 떨어지는 것 같아요. 약간 "억지로 돌아가게만 만들자"라는 느낌입니다. 그래서인지 비효율적인 코드처럼 보입니다. 좀 더 좋은 방법이 있을지 조언을 구하고 싶습니다 😔
=> Week2 [STEP 2] mmim

CodeStarterCamp_Week2/main.swift
@Journey36 
글렌님! STEP3 PR 보냅니다😁
**고민되었던 점** 
1. 네이밍 재정비 
모든 네이밍을 다시 한번 생각해 보는 시간을 가졌습니다. 
그 과정에서 불필요하게 선언해 주었던 변수들의 계수를 줄여 네이밍이 더욱 편리하게 만들었습니다. 
2. 옵셔널 바인딩 
연습문제를 덕분에 옵셔널 바인딩 파트에서 수월히 넘어갈 수 있었습니다. 
dictionary에서 값을 빼올 때 default 값을 주면 optional 이 아닌 형태로 빼올 수 있다는 것을 발견하였는데, 
아무리 생각해도 지정해야 할 마땅한 default 값이 없어, optional 바인딩을 사용했습니다.
4. scope 에 관하여
스터디를 하면서 scope 에 대해서 이야기를 나누고 코드에 조금더 적용해 보아야 겠다고 생각했습니다. 함수 안에서 다른 함수에 안에 있는 변수를 왜 불러올 수 없는지 등등 궁금증이 많이 해결 되었고 Global 변수를 많이 선언하는 것이 안 좋다고 하여 최대한 지양하려고 하였습니다.
**조언을 얻고 싶은 부분**
* 여기서 코드를 더 발전 시킨다면, 
matchedNumbers 도 매 회차마다 같이 저장 하고 싶은데요, 
dictionary 말고 다른 자료형을 사용해야 할까요? 
아니면 [String: Array] 형태로 dictionary 를 활용하는 것이 좋을까요? 
아니면 새로운 dictionary (기존것과 분리된) 를 만드는 것이 좋을까요? 
* Global 변수를 많이 선언하는 것이 안 좋다.
는 것에 대한 이유를 찾아보니 
값이 변경되는지 추적이 어렵다. 라는 이유가 공통적으로 나오는데 …
=> Week2 [STEP 3] cherrishRed

README.md
=> Week2 [STEP1] Minseong-yagom

CodeStarterCamp_Week2/main.swift
=> Week2 [Step2] Taeangel

CodeStarterCamp_Week2/main.swift
@Neph3779 
random()을 이용해서 1부터 45사이의 랜덤 숫자를 뽑아서 Set 타입 변수에 저장했습니다.
겹치는 번호를 비교할 때 Set 타입 intersection 을 이용하였고 출력을 할 때 번호 뒤에 , 를 넣기 위해 if 문을 사용해 봤습니다.
=> week2 [STEP2] doylehong

CodeStarterCamp_Week2/main.swift
로또 번호를 생성하는 함수와, 내 번호와 로또 번호를 맞추는 함수를 생성했습니다.
- 해결한 문제 : 로또번호가 5개만 생성되는 오류
: 로또번호 생성하는 makeLottoNumbers에서 처음에 for문으로 6번 반복하는 코드를 짰지만, print 로 숫자를 확인해보니, 중복된 숫자가 선택될 경우 로또번호가 5개만 생성되는 오류가 있어서, lottoNumbers.count < 6일때 동안만 반복하게 하는 코드로 수정했습니다. @Tak95
=> Week2 [STEP 2] 

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/LottoMaker/LottoFactory.swift, CodeStarterCamp_Week2/LottoMaker/NumberPicker.swift, CodeStarterCamp_Week2/main.swift
@joey-ful 
반갑습니다! STEP 2 PR 드려요! 😉
고민했던 점
* STEP 1 에서 작성한 순서도를 따라 함수 생성하기
* 두 배열 간 겹치는 element 추출하기
* 출력 결과 값 지정하기
1) STEP 1 에서 작성한 순서도를 따라 함수 생성하기
무작위로 6개의 숫자를 생성하여 배열로 만드는 LottoPicker 함수를 만들어 보았는데요, 다른 방법이 있더라도 최대한 순서도를 따라가려고 했습니다. 소스코드를 작성하고 보니 피드백 주신 대로 숫자 범위가 빠져있다는 걸 알게 되었네요🧐
2) 두 배열 간 겹치는 element 추출하기
처음에는 배열의 요소를 각각 접근하여 비교하였는데요, 혹시 다른 방법이 없을까 찾아보다가 filter라는 메서드를 적용해 보았습니다.
지난 번에 말씀해주셨던 for문을 고차함수로 대신 사용하곤 한다는 게 이런 방법인가 싶었습니다!
(알고보니 다른 언어에도 동일한 개념이 다 있었군요.. Java에도 `Arrays.stream(arr).filter("조건")` 으로 사용 가능하다는 걸 저는 몰랐습니다...😱)
3) 출력 결과 값 지정하기
전달받은 배열이 빈 배열인지 조건문을 통해 확인하고 결과에 맞는 comment를 출력하도록 했습니다.
(질문) 혹시 Optional을 사용한다면 
```swift
if compareResult.isEmpty {
comment = "아쉽지만 겹치는 번호가 없습니다."
} else {
....
}
```
소스코드처럼 배열 크기 체크를 건너뛸 수 있을까요?
=> Week2 [STEP 2] Grumpy

CodeStarterCamp_Week2/Step3.swift
@Ldoy  안녕하세요 타코캣님! Step3도 잘부탁드립니다.
---
> ```func saveLottoNumbersToDictionary()``` 에서  ```print(lottoNumbersDictionary)```은 요구 조건에는 없지만 잘 저장됐는지, 해당 회차의 번호가 맞는지 확인하기 위해 넣은 코드입니다.
* ```func checkLottoNumbers()``` 은 원하는 회차를 매개변수로 입력받아 해당 회차를 출력하는 함수입니다. 해당 회차의 ```lottoNumbersDictionary``` Value값에 안전하게 접근하기 위해 optional binding을 사용했습니다. 아래는 몇가지 궁금한 점입니다.
> 1. 저는 Key 값이 존재해도 Value 값이 없을 경우를 생각해서 Value 값을 받기 위해 optional binding을 사용했습니다. 이러한 생각에서 optional biding을 사용한 것이 맞는 접근 방법일까요?
> 2. 저는 key값을 매개변수로 받아서 value값에 접근하였는데 이쯤에서 드는 생각이 "key값 또한 있을지 없을지 모르는데 이것 또한 optional을 생각해야하지 않을까?" 라는 생각입니다. 만약 optional을 생각해야한다면 key값을 optional binding한 후 value값을 optional binding하는 이중 작업을 해야하는 것일까요. 
* 생각이 얽혀서 글로 고민을 표현하기 어려웠습니다 ㅜㅜ
=> Week2 [STEP 3] mmim

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/main.swift
=> Week2 [STEP2] Minseong-yagom

CodeStarterCamp_Week2/main.swift
=> Week2 [STEP 3] Taeangel

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/main.swift, CodeStarterCamp_Week2/week2_step2.swift
수지 안녕하세요! step2 PR 보냅니다.
- generateLottoNumbers
step1에서 만든 순서도를 코드로 짠 함수입니다. Set이니까 중복인지 검사할 필요 없이 그냥 insert만 사용했습니다.
- getMatchedNumbers
Set에서 교집합을 이용해 겹치는 숫자를 구했고, 원래는 Set을 반환하려고 했는데 오름차순 정렬하려고 sorted()를 썼더니 배열로 바뀌어서 배열을 반환하는 걸로 변경했습니다.
- changeArrayToString
배열 출력 때 괄호를 없애려고 만든 함수입니다. joined 메소드를 알게 되어 사용하려고 했었는데 조건에 맞추려면 오히려 더 조작을 많이 해야 했어서 그냥 String에 하나씩 넣어주고 마지막에 남는 것을 지우는 식으로 만들었습니다.
이번 스텝은 옵셔널 개념을 사용하지 않아서 무난하게 구현했습니다. 
이번에는 출력하는 것까지 미션이어서 main 파일에 여러 변수들을 지정해놓고 함수를 이용해서 대입한 다음, 결과 출력하는 함수를 호출해 출력했습니다. 그런데 이렇게 하면 main 안에서 선언한 변수들이 전역 변수가 되는 거 아닌가요? 전역변수는 에러가 날 수 있고 속도도 느리게 하니까 최대한 안 쓰는 게 좋다고 생각하는데, 그래서 찾아본 해결책이 private이었습니다. private을 쓰면 해당 범위 안에서만 쓸 수 있다고 해서, main 안의 변수들을 private let으로 선언해서 사용했더니 결과가 잘 나왔습니다(현재는 private 안 쓴 상태로 푸시한 코드입니다). 아직 private 개념을 잘 아는 게 아니어서 그런데 이렇게 사용해도 되는 …
=> Week2 [STEP 2] venniek

CodeStarterCamp_Week2/main.swift
@Kioding 
안녕하세요 키오! 
이번 2주차 STEP 2 과제를 완료하여 이렇게 PR요청을 드려봅니다!
항상 꼼꼼한 리뷰 감사드립니다 ㅎㅎ 😁
+ `compareMyLottoNumbers` 메서드 내의 변수 `myLottoNumbers` 와 `winningNumbers`를 새로운 `Int` 타입의 Set 콜렉션 변수에 담아주었는데 네이밍을 정하는게 쉽지않았습니다.. 제 나름대로 고민해서 네이밍을 정해주었는데 괜찮은지 모르겠네요 ㅎㅎ 😅
+ `myLottoNumbers` 와 `winningNumbers` 를 비교하기 위해서 기존에 선언된 array 타입의 콜렉션을 Set 타입의 콜렉션으로 바꿔주고 비교해주었는데 이게 맞는 흐름인지 궁금합니다..!
=> Week 2 [STEP 2] vayne

CodeStarterCamp_Week2/main.swift
feat : 딕셔너리에 로또번호 저장하는storeLottoNumbers 함수 생성, 임의 회차의 로또 번호 출력할 수 있는 printAnyLottoNumbers 함수 생성
refactor : makeLottoNumbers 함수에서 생성한 로또번호를 다른 함수에서도 사용할 수 있도록 makeLottoNumbers 함수에 리턴값을 추가함, printAnyLottoNumbers에 파라미터 추가
1. makeLottoNumbers 함수에 return 값을 추가했습니다. lottoNumbers가 makeLottoNumbers 함수 내의 지역변수로 생성되어 다른 함수에서 사용하기 어려워서, 함수가 return 값으로 lottoNumbers를 갖도록 했습니다.
2. 로또 번호가 생성될 때마다 lottoDictionary에 회차와 로또 번호를 추가하기 위해 lottoNumbers를 파라미터로 받는 storeLottoNumbers를 생성했고, makeLottoNumbers 내에서 호출했습니다.
3. 로또번호를 dictionary에 저장하는 storeLottoNumbers 함수를 만들었습니다. 함수 내에서 회차를 나타내는 index가 함수가 호출될 때마다 1씩 증가하도록 했습니다. 그리고 함수가 호출될 때마다 dictionary에 각 회차마다 lottoNumbers를 추가했습니다.
4. checkLottoNumbers 함수는 전역변수인 myLottoNumbers를 파라미터로 받고, 그 파라미터와 makeLottoNumbers의 리턴값의 교집합인 matchedNumbers 배열을 생성했습니다.
5. …
=> Week2 [STEP 3] marisol

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/Step2.swift, CodeStarterCamp_Week2/main.swift
@Kioding 
키오 안녕하세요!
오늘 step2를 빨리 pr하고 싶어 출근전에 열심히 커밋 했습니다 ㅎㅎ
- 고차함수
배열에 들어있는 값 비교할때 전에는 항상 for문 2개를 사용했었는데
몇달 전 알고리즘 문제를 풀다가 filter라는 고차 함수를 알게 되었습니다.
이번에 사용해 봤는데 코드가 훨씬 간결해지고
그렇다보니 파악하기도 편해지네요!
=> Week2 [STEP 2] hogang1223

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/main.swift, CodeStarterCamp_Week2/step2 Ex1.swift.swift, CodeStarterCamp_Week2/step2 Ex2.swift
@Tak95 !  스텝2 pr 입니다!
step1에서 진행한 순서도를 토대로
함수를 만들어 랜덤한 번호를 생성해 set타입에 결과값을 6개 저장하도록 구현한뒤
step2에서 제시된 Array 타입의 값들과 비교하여 겹치는 번호가있는지 확인후 출력하는 기능을 구현하였습니다
**고민한점**
step2에서 제시된 값들은 Array 타입이기때문에 
만들어둔 랜덤한번호를 생성하는 함수의값이 저장된 Set 와 비교를 하기위해선
어느한쪽의 타입을 변경하여 비교를해주어야했습니다
Set타입을 Array 타입으로 변경하여 비교를 하는것보다
step2 문제값을 Set타입으로 변경해주어 intersection 메소드를 사용하는게 효율적으로 생각되어 
Set 타입으로 변경하여 사용 비교 하였습니다
함수의 값들을 반환 하여 사용하는 형태로 만들게되니 함수를 의도치않게 2,3번 호출하게되거나 값이 변경되는 상황이 생겨
함수의 값을 반환하는 형식이아닌 프로퍼티를 선언해주어 함수를 호출하게되면 변경된 값들이 선언한 프로퍼티에 저장되게끔 만들어주었습니다
이렇게 변경하여 사용하니 가독성이 조금더 좋아진것같습니다
함수를 반환하는 형식으로 사용했을때에는 어떤 함수인지 무슨기능인지 한번씩 보고 이해해야할 시간이필요했다면 프로퍼티를 선언후 값을 할당하는 방식으로 변경하니 선언된 프로퍼티만 보고도 이해하기 쉬워진것같습니다
=> Week2 [STEP 2] malrang

README.md
@Kioding
step1 입니다
최상위 경로에 있는 README 파일에 순서도 첨부했습니다
피드백 부탁드리겠습니다 :)
=> week2 [step1] iilim

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/CreateLottoNumber.swift, CodeStarterCamp_Week2/main.swift
- @Ldoy 
- Step 2
코드를 작성하면서 main 파일에 모든 코드를 작성하는 것보다 새로운 파일을 만들어서 코드를 작성하는 것이 관리에 편할 것 같아
새로운 파일을 하나 더 생성하여 작성하였습니다.
처음에 random함수를 찾다가 도저히 못찾겠어서 같은 스터디원의 도움을 받아 난수를 Int 타입으로 생성하는 함수를 사용하였습니다.
그리고 겹치는 번호를 출력하는 부분에서 지금 코드는
```swift
축하합니다! 겹치는 번호는 [1, 2] 입니다!
````
로 출력되는데 저 대괄호를 없앨 수 있는 방법을 찾아보다가 도저히 모르겠어서 우선 푸시했습니다 ㅠㅠ
=> Week2 [Step 2] 안경줄복학생

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/LottoDictionary/LottoDicManager.swift, CodeStarterCamp_Week2/LottoMaker/LottoFactory.swift, CodeStarterCamp_Week2/Utils/IntArrayToStringConverter.swift, CodeStarterCamp_Week2/Utils/NumberPicker.swift, CodeStarterCamp_Week2/main.swift
@joey-ful 
안녕하세요 joey! 
STEP 3 Pull Request입니다! 이미 작성한 줄 알았는데 커밋만 해놓고 PR을 작성하지 않았더라구요ㅠㅠ
그리고 지난 번 코멘트에 대해 생각해 보았는데요, 주석을 달아줌으로써 보는 사람의 이해를 돕는 목적도 있겠지만 가장 좋은 방법은 한눈에 봐도 이해하기 쉬운 코드를 작성하는 것이라고 생각이 드네요! 반대로 함수 네이밍만 보고도 동작을 이해할 수 있도록 작성한다는 게 어떤 의미인지 조금씩 알 것 같습니다 ㅎㅎ
본분을 지키지 못한 코드에 주석으로 자세히 써놓는 것이 과연 의미가 있었을까요? 아마 지난 번 Joey가 거듭 강조해주신 이유가 그 때문이 아닐까 추측해봅니다..🧐그래서 이번엔 최대한 Naming으로 동작을 표현할 수 있도록 만들어봤어요. 그러다 보니 자연스레 함수형 프로그래밍에도 좋은 연습이 되는 것 같아요.
오늘 날씨가 굉장히 추워졌네요 추위 조심하세요!🤗
=> Week2 [STEP 3] Grumpy

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/main.swift, CodeStarterCamp_Week2/week2_step3.swift
@SoKoooool 
수지 안녕하세요! week2 step3 PR 보냅니다.
- getListOfWinNumbers
로또 당첨 번호를 담아두는 딕셔너리를 만드는 함수입니다. 처음에는 프린트하는 코드를 한꺼번에 넣었는데, 한번 딕셔너리를 만들고 나면 다시 접근할 때 같은 번호가 나오는 게 맞는 거 같아서 딕셔너리를 만들어서 변수에 넣어놓고, 그 변수를 프린트하는 함수에 넣어서 출력하도록 했습니다.
이 문제에서는 5번을 만들지만 숫자를 받아 만들 수 있도록 `count` 매개변수를 넣어줬습니다. step2에서 만들었던 `generateNumbers`는 `Set<Int>` 형식을 반환해서, 정렬도 되면 좋을 거 같아서 `sorted()` 메소드 사용해서 [Int]로 만들어줬습니다.
- printNthOfList
`list` 에서 n번째 로또 당첨 번호를 찾아 출력하는 함수입니다. 딕셔너리 값은 없을 수도 있는 `optional`로 반환되기 때문에 `if let` 구문 사용했습니다. 받아온 번호를 출력할 때는 step2에서 만들었던 `changeArrayToString` 사용했습니다. 
- main
딕셔너리를 한번 만들어서 저장할 `listOfNumbers`는 바꾸지 않기 때문에 상수로 만들었습니다. 이번 문제에 맞게 `count`를 5로 보내줬고 그 후 print하는 함수에 N을 2로 넘겨 출력했습니다. 미리 딕셔너리를 저장했기 때문에 print를 다시 한번 하면 결과가 똑같이 나옵니다.
짜다보니 옵셔널이 한 번밖에 안 쓰여서 약간 아쉬운(?)데ㅎㅎㅎ 우선 이렇게 만들어봤습니다!
=> Week2 [STEP 3] venniek

CodeStarterCamp_Week2/main.swift
@jgkim1008 
Set 컬렉션의 멤버를 하나씩 뽑으려고 헀더니  Set는 인덱스로 접근해서 뽑을 수가 없더군요 ㅜㅜ  
Set의 멤버 하나하나를 꺼내는 방법을 구글에서 온갖 검색단어로 검색 했더니 어디에도 없어서 이것저것 해보았습니다.
그러다가 그냥 Set 그대로 뽑자하고 sorted함수를  사용해 정리하였더니 오류가 사라졌습니다. 저는 거기서 뭐지 싶어 
sorted함수를 찾아보기 시작했습니다. sorted함수는 정렬된 배열로 다시 리턴해주는 속성이 있는걸 깨닫고 실험을 해봤습니다 
Set를 sorted함수를 이용해 새로운 변수에 넣어 주고 타입이 Set<Int> -> [Int]로 이용 가능 한 것을 확인했습니다.
---
회차와 번호를 저장해주는 함수를 만들고
호출할때마다 저장해줘야 하기에 saveInDictionary함수를 createWinningNumbers함수에서 호출 하였습니다. 
출력은 회차 번호를 받아 그에 맞는 번호가 있으면 출력해주는 방식으로 코드를 작성했습니다.
=> Week2 [STEP 3] Minseong-yagom

CodeStarterCamp_Week2/main.swift, CodeStarterCamp_Week2/step2.swift
@Kioding 
step2 입니다
어려운 점은 딱히 없었습니다
피드백 부탁드리겠습니다 :)
=> week2 [step2] iilim

CodeStarterCamp_Week2/main.swift
@jgkim1008  
많이 늦었죠 ㅠㅠ pr 보냅니다. 일단 ! 제가 작성한 순서도 를 보고 로또 당첨 번호를 생성 하기가 쉽지않더라고요... 
순서도 에는 맞지않지만 로또 당첨 번호 기능 구현 까지하고 내가 찍은 번호와 로또당첨 번호를 비교 출력 하는 기능까지 구현 했는데
축하합니다! 겹치는 번호는 1, 2, 3, 4, 5, 6 입니다! < 요구사항처럼 안나오고  
축하합니다! 겹치는 번호는 [1, 2, 3 ] 입니다 ! < 제 코드에서는 대괄호를 포함해서 나오더라고요.. 여기서 어떻게 해야할지를 모르겠습니다 🙀
부족하지만 pr 보냅니다
=> Week2 [Step 2] 051kid

CodeStarterCamp_Week2/main.swift
=> Week2 [STEP2] Leebumju

.gitmessage.txt, CodeStarterCamp_Week2/main.swift
@SoKoooool 
안녕하세요 `Sooji`!
하나의 function을 구현할 때마다, `commit`을 했어야 했는데
조급한 마음에 결과값이 나온 후에야 `commit`을 했습니다,,,, 다음부턴 꼭 `feature`가 추가될 때마다 `commit` 실시하겠습니다 😅 
***
이번 `STEP2`에서 가장 고민했던 부분은 `일치하는 결과값을 String으로 나열하는` 부분이었습니다.
처음에는 단순히 `Array`로 선언한 변수 `matchedNumbers`에 `append`를 한 후, 
```swift
result = `일치하는 번호는 \(matchedNumbers)입니다.'
return result
```
위와 같은 방식으로 출력을 했지만, TODO와 다른 결과값이라는 것이 마음에 걸려 더 고민하였습니다.
`String`에 대한 `공식 문서`를 참고하여, `Accessing String Elements`의 예제를 참고하여 코드를 구현하였습니다.
```swift
for i in 0...myLottoNumbers.count-1 {
if (lottoNumbers.contains(myLottoNumbers[i])) {
matchedNumbers += "\(myLottoNumbers[i]), "
} else {
continue
}
}
let lastSpace = matchedNumbers.lastIndex(of: ",") ?? matchedNumbers.endIndex
let removeCommaNumbers = matchedNumbers[..<lastSpace]
if (matchedNumbers.count > …
```
=> Week2 [STEP 2] 고도

CodeStarterCamp_Week2/main.swift
@SoKoooool 
안녕하세요 `SooJi` 😀  먼저 새해 복 많이 받으세요 :) 새해가 밝았네요,,,,
그래도 STEP은 진행해야 할 것 같아서 PR 드립니다!!
이번엔 기존에 문제가 많이 되었던 `Naming`부분에 신경을 썼습니다.
`당첨 기록`을 조회하는 것이기 때문에 단순한 `lottoNumbers`로 선언하지 않고
`winningHistory`로 진행했는데, 해당 `Naming`에 꼭 `lotto`가 들어가야 하는가야 하는지 의문이 들더라구요!
확인 후 리뷰 부탁드리겠습니다!
감사합니다:)
=> Week2 [STEP 3] 고도

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/main.swift, CodeStarterCamp_Week2/matchLottoNumbers.swift, CodeStarterCamp_Week2/saveWinningNumbersLog.swift, CodeStarterCamp_Week2/searchWinningNumbersLog.swift
@Kioding 
안녕하세요 키오!
week2 STEP3 과제를 완료해 이렇게 PR 요청을 드립니다.
많이 늦게 보내게 되어 죄송합니다..ㅠㅜ 😂
항상 꼼꼼한 리뷰 감사드립니다 😁
=> Week2 [STEP3] vayne

CodeStarterCamp_Week2/main.swift
@1Consumption 
올라프님!
이번 스텝은 내번호와 맞춰보기 였습니다.
제가 찍은 번호와 랜덤으로 생성된 번호가 몇개나 겹치며 그 결과에 따라
겹치는 번호를 포함한 문구를, 또는 "아쉽지만 겹치는 번호가 없습니다"를 출력하는 프로그램을 구현했습니다.
많은 조언 부탁드립니다! 항상 감사합니다!
=> Week2 [STEP 2] KayAhn

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/main.swift
@hcooch2ch3 
안녕하세요 🌰 
스텝2 PR 보냅니다!
처음완성했을때 결과 출력시 
```markdown
축하합니다! 겹치는 번호는 [1] 입니다!
```
위에처럼 [] 가 같이나와서 printMatchingNumbers 함수를 
추가하여 해결했습니다. 👍 
```markdown
축하합니다! 겹치는 번호는 1 입니다!
```
=> Week2 [STEP2] moook

CodeStarterCamp_Week2/main.swift
=> Week2 [Step2] ohkyeongsik

CodeStarterCamp_Week2/main.swift
@TTOzzi 
안녕하세요 또치님😊
Dm 드렸었는데, 제가 '함수'에 대한 이해를 잘못 하고 있었다는 것을 깨달았습니다,,!
return과 print의 차이점을 잘 몰랐습니닿ㅎ 제가 모른다는 걸 몰랐다는 게 가장 시간이 많이 걸렸던 부분이었습니다😅
그래서 다시 공부하고 작성해서 커밋합니다ㅎㅎ
그리고 myLottoNumbers는 1...6이 아니라 제가 넣고 싶은 번호로 넣어봤습니다ㅎㅎ
```swift
let myLottoNumbers: [Int] = [5, 13, 23, 25, 37, 42]
```
항상 감사합니다ㅎㅎ
+) 이번 push를 할때 소스트리에서 마지막 커밋과 동시에 push를 해서 그런지 순서도까지 같이 다시 push된 것 같습니다..! 다음엔 이때까지 했던 방법대로 커밋한 것만 push 하겠습니다~!
=> Week2 [STEP2] lia388

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/Lotto.swift, CodeStarterCamp_Week2/main.swift
@1Consumption 
안녕하세요 올라프님!
Week2 Step 3 미션은 "로또 당첨 번호를 회차별로 저장하고, 확인하자!" 였습니다.
To Do List에서 프로그램 구현을 위해 해야 했던 작업은..
1. 회차와 로또 번호들을 저장하는 Dictionary 타입의 변수를 생성
2. Step2의 로또 당첨 번호 생성 함수를 호출할 때 마다, 회차와 로또 번호를 Dictionary에 저장하도록 동작하는 함수 구현
3. 로또 당첨 번호를 5번 생성
4.  Dictionary 에서 2회차의 로또 당첨번호를 찾는다.
5. Optional 값을 안전하게 추출한다.
6. 추출한 값을 예제처럼 출력한다.
항상 저를 위한 코멘트 달아주셔서 감사합니다!
=> Week2 [STEP 3] Kay Ahn

CodeStarterCamp_Week2/main.swift
@Babywalnut 
안녕하세요 바비 ! ㅎㅎ 
이번 스텝에서는 로또번호를 생성하고, 그 로또번호를 자신의 번호와 맞춰보는 함수를 구현하였습니다.
1. 로또번호는 중복되는 숫자가 없어야하기 때문에 Set을 이용하여 구현하였습니다
Set에 랜덤으로 만든 Int값을 넣고 그 개수가 6개가 되면 출력해주는 방식으로 구현하였습니다.
2. 로또번호를 확인하는 함수를 구현하였습니다.
Set내에 구현되어있는 메서드 중에 교집합 메서드가 있다는 것이 생각나서 이를 활용하였습니다.
겹치는 번호를 출력해주기 위해서 joined를 활용하였습니다.
joined는 컬렉션의 값들 사이를 seperator로 연결하여 결합해주는 메서드입니다. :)
요구하는 조건이 이와 잘 어울린다고 생각하여 joined를 사용해주었습니다.
=> Week2 [STEP 2] ohtt

CodeStarterCamp_Week2/main.swift
@Journey36 안녕하세요 글렌님! 좋은 주말 보내고 계신가요 ㅎㅎ
1. Array로 구현을 시도하다 Set으로 컬렉션 타입을 변경하였습니다
-- > 중복 확인 과정에서 생각이 멈추는 바람에 중복을 잡아주는 Set으로 변경했습니다 !
2. print하는 과정에서 배열로 출력하다보니 대괄호 제거 방법을 생각해내지 못했습니다..
--> 피드백 부탁드리겠습니다 !
3. 코드가 전체적으로 아쉽다고 생각이 듭니다..
--> 전체적으로 피드백 부탁드리겠습니다! 감사합니다! 좋은 주말 되세요😃
=> Week2 [Step2] seokzihan

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/Step2.swift, CodeStarterCamp_Week2/Step3.swift, CodeStarterCamp_Week2/main.swift
@Monsteel 
내가 만들고 내가 즐기는 로또
사행성 코딩;;
=> Week2 [Step2] JeeeeSang

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/main.swift, CodeStarterCamp_Week2/step3 로또번호저장.swift, CodeStarterCamp_Week2/step3.swift
@YebinKim 
안녕하세요 비비 ㅎㅎ
Week2-Step 3 과제 제출합니다.
main.swift에서는 step2의 코드를 주석처리하고 step3의 함수만 실행해주었습니다!
첫 번째로 회차와 로또 번호들을  lottoHistory 라는 이름의 Dictionary 타입의 변수에 저장되도록 했습니다.
두 번째로 generateRandomNumber() 함수를 통해 6개의 랜덤한 숫자를 set타입의 변수 makingNumbers에 저장되도록 했습니다.
세 번째로 로또 당첨 번호 생성 함수를 호출할 때마다, 회차와 로또 번호를 Dictionary에 저장하도록 하는 함수 saveLottoNumber를 선언해주었습니다.
네 번째로 함수 호출부에서 적어준 endRound 만큼 saveLottoNumber를 실행하여 딕셔너리에 저장되도록 해주었습니다.
마지막으로는 함수 searchLottoNumber()를 선언해서 원하는 회차를 입력하면 
"\(round)회차의 로또 당첨 번호는 \(joinedStr) 입니다." 를 출력하도록 하는 함수를 구현해주었습니다.
제가 저번 step2 에서 전역변수와 지역변수의 차이점에 대해 여쭤봤었는데, 비비가 지역변수와 전역변수는 어느 시점에 초기화 되는지, 함수를 여러번 호출했을 때 항상 일정한 값을 유지하는 지를 고민해보라고 하셨는데요!
```
var makingNumbers = Set<Int>()
func generateRandomNumber() -> Set<Int> {
while makingNumbers.count < 6 { …
```
=> Week2 [STEP 3] yeeton

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/Step2.swift, CodeStarterCamp_Week2/Step3.swift, CodeStarterCamp_Week2/main.swift
전역변수를 사용하지 않는 방식에 대해 고민해 보았습니다.
@Monsteel
=> Week2 [Step3] JeeeeSang

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, step3/main.swift
@Journey36 
안녕하세요 글렌님! step 3 입니다 !
- 저번에 말씀해주신 joined(separator: )를 이용해서 코드를 작성해 보았습니다.
- 컬렉션 타입 선언을 일관성 있게 진행했습니다.
- 옵셔널 값은 nil-coalescing을 사용해서 간편하며 안전하게 추출해보았습니다!
항상 감사합니다 ! 좋은 하루 되세요 !
=> Week2 [Step3]

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/main.swift, CodeStarterCamp_Week2/step2.swift
@Journey36 
안녕하세요 글렌님~
요즘 갑자기 추워져서 그런지 감기에 크게 시달리고 있습니다 ㅎ..
감기 항상 조심하세요!
피드백 항상 감사드립니다~😃
=> Week2 [STEP 2] Makseong2

CodeStarterCamp_Week2/main.swift
@Journey36 글렌님 안녕하세요 step3까지 해봤습니다!
우선 코드를 작성하면서 힘들었던점은 회차별로 값을 저장하는 방법이었습니다 .
제가 처음에 작성한 코드로는 랜덤으로 뽑히는 위에 함수를 리턴 값으로 받아서 회차별로 호출 했었는데 
고정되어 있는 값이어야 한다고 생각해서 호출 된 번호를 옮겨서 저장해 보았습니다. 
사실 전체적으로 어떻게 작성 해야 할지 갈피를 잡기가 힘들었습니다. 이게 맞는지 저게 맞는지 많이 고민했는데,
정답은 없으니 제 생각대로 한번 작성 해봤습니다 피드백 잘 부탁드립니다!
감사합니다 글렌님!!
=> Week2 [STEP3]Daosn3027

CodeStarterCamp_Week2/main.swift
=> Week2 [STEP 3] 3_ohkyeongsik

CodeStarterCamp_Week2/main.swift
@Babywalnut  
PR관련 도움주셔서 감사합니다 바비!  
이번에 STEP2를 진행하면서 상당히 어려웠었는데요  
- ## 랜덤함수를 생성하는 변수  
일단 STEP1의 제목이 로또 당첨번호 생성기 순서도 생성하기 였기 때문에 함수의 이름은 lottoNumberGenerator로 고쳤습니다.  
또한 이 함수를 생성할 때에 랜덤숫자를 생성하는 함수 내에서 반복문 밖에 랜덤숫자를 생성하는 변수를 만들면 이미 변수가 선언이 되서 무한루프에 빠지게 된다는 것을 알고 반복문 안에 랜덤숫자를 생성하는 변수를 넣어주었습니다😵‍💫  
- ## joined  
다른건 다 문제없이 프린트가 되었는데 제가 만든 함수에서는 겹치는 번호가 대괄호와 함께 프린트가 되었습니다.  
어떻게 할지도 모르겠는데 뭐라고 구글에 검색해야 나오는지도 몰라서 우여곡절끝에 파이썬 언어에서 이와 같은 문제를 .join()이라는 메소드를 사용한다는 것을 찾았고 swift에도 비슷한 성격의 메소드가 있을것 같다 생각해서 swift join을 찾아보니 .joined라는 메소드가 있었습니다!!  
그런데 제가 사용한 컬렉션 Set 타입에서는 .joined가 사용되지 않았고, swift 공식문서 Set, joined를 참고해보니 변경되지 않는 sequence를 위해 .map(String.init)이란 메소드를 사용한다는 것을 알게되었습니다..!  
여기까지 오는데 정말 우여곡절이 많았지만 혼자서 방법을 찾은거에 대해 만족하겠습니다!  
혹시나 다른 방법이나 더 간결한 표현이 있다면 피드백 부탁드리겠습니다
- p.s.  
만약 바비라면 대괄호를 빼고 …
=> WEEK2[STEP2]김동용

CodeStarterCamp_Week2/main.swift
@Babywalnut 
안녕하세요 바비 ! ㅎㅎ week2 step3 PR 드립니다.
- `guard let` 구문을 이용해서 해당 회차의 lottoNumber가 nil이면 함수를 종료시키도록 구현했습니다 :)
- `if let`이 아니라 `gaurd let` 을 사용한 이유는 해당 회차의 로또번호가 없으면 아래 print 관련된 부분을 
실행시킬 이유가 없기 때문입니다 :)
=> Week2 [STEP 3] ohtt

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/main.swift, CodeStarterCamp_Week2/step2.swift, CodeStarterCamp_Week2/step3.swift
@Journey36 
글렌님 안녕하세요~
step3 push 합니다 ㅎㅎ
개인적으로 이번주차에 시간이 많이 들거 갔네요 ㅎㅎ
(시간이 많이 들어 갔다는것은, 조금더 깔끔하고 알아먹기 쉽게 작성할려고 노력하였습니다.
추가로, 컬렉션들의 차이들도 확연히 깨달을수 있는 회차 였습니다. )
감사합니다!
=> Week2 [STEP 3] Makseong2

CodeStarterCamp_Week2/main.swift
@hrjy6278 
안녕하세요 지스님!
Week2-step2 과제를 구현하였습니다.
Step1 순서도와의 다른점
1. Array 대신 Set을 이용하여 구현하였습니다.
2. 6번 반복하는 대신, 무한루프를 이용하였습니다.
질문
Q1. Set을 print함수에서 출력하려 할 때, "[1, 2, 3, 4, 5"]" 와 같이 대괄호가 같이 포함되는 문제가 발생하였습니다.
이를 없애줄 메소드를 찾았으나, 결국 찾지 못하여
printSet이라는 함수를 정의하여 Set을 출력하는 함수를 구현하였습니다.
혹시, 대괄호를 없앨 수 있는 메소드가 있는지 궁금합니다!
=> Week2 [Step2] SEO-YJ

CodeStarterCamp_Week2/lottoNumbers.swift, CodeStarterCamp_Week2/main.swift
@uuu1101 
안녕하세요 태태! week2 step2입니다😊
set을 사용하여 중복된 숫자가 없게 하였고, intersection을 사용하여 생성된 번호와 저의 번호 중에 겹치는 숫자들을 matchNumbers에 저장하였습니다. 
그리고 isEmpty를 사용하여 matchLottoNumbers가 비어있지 않은 경우 해당 숫자들을 출력하게 하였습니다.
출력하면 대괄호가 자꾸 출력돼서 그부분에 시간을 많이 쏟았네요💦
map을 사용하여 String으로 변한해준 뒤 join을 이용하여 배열의 문자열들을 하나의 문자열로 반환해줄 수 있다는 것을 알게 되어 해결할 수 있었습니다!
감사합니다~!
=> Week2 [STEP 2] uuuni

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/main.swift, CodeStarterCamp_Week2/step 2_checkLottoWinner.swift, CodeStarterCamp_Week2/step 3_storeLottoNumbers.swift
@YebinKim 
안녕하세요, 비비! 🥰
2주차 마지막 과제 PR 드립니다! 🚀
(로켓 이모지를 쓰기엔 진도가 좀 늦지만요.. 🥲)
이번 과제는 평소보다 더 재미있었어요.
Step 3 첫 커밋과 두번째 커밋을 둘 다 봐주셨으면 좋겠어요..!! 🙏
checkLottoWinner 함수에서 대괄호 없는 출력을 위해 Set<Int>를 Array<String>으로 바꾸는 코드가 있었는데, 
이걸 따로 함수로 정의했어요. 깔끔해져서 기분이 좋아졌어요!
> 🙋 질문 1 : 대신 아래의 코드가 뭔가 중첩의 중첩의 중첩 같은 느낌이라 가독성이 떨어지는 것 같기도 한데, 비비는 어떻게 생각하시나요?
``` swift
print("축하합니다! 겹치는 번호는 \(convertingIntSetToStringArray(winningNumbers).joined(separator: ", ")) 입니다!")
```
이걸 다 작성하고 커밋할 때, '함수 하나 쓸 때마다 커밋을 했어야 했는데..!' 라는 생각이 들어서 아쉬웠어요.
돌아가게 만드는 거에만 정신을 쏟았던 것 같아요.
> 🙋 질문 2 : Promote Clear Usage (이 문장.. 외워버렸네요) 를 위해 우선 데이터 타입을 최대한 없애봤어요. 어떤 점을 더 개선하면 좋을까요? 비비가 읽을 때 변수의 네이밍이 가독성은 좋은지, 의미는 잘 와닿는지 궁금해요.
> 🙋 질문 3 : 윗 문장에도 불구하고, 아래의 함수는 변수명에 거의 데이터 타입만을 썼어요. 이 함수는 단순히 데이터 타입을 변경하기 위한 함수이고, 변수명도 오히려 의미를 담기보다는 데이터 타입이 어떻게 변해가는지를 …
=> Week2 [STEP 3] mskaang

CodeStarterCamp_Week2/main.swift
@Babywalnut 안녕하세요 바비!  
이번 스텝 3 PR보냅니다!!  
---
- 이번 스텝 3를 진행하면서 스텝 2에서 사용한 lottoNumberGenerator을 사용하고 싶었지만 해당 함수는 set<String>값을 반환해주기 때문에 `["1", "2", "3", "4", "5", "6"]이런 식으로 출력이 되지만`해당 스텝에서 원하는 출력은 `[1, 2, 3, 4, 5, 6]`으로 출력되길 원했기에 다시 스텝 2의 모든 함수들을 고치기엔 머리가 복잡해질 것 같아서 `arrayLottoNumberGenerator`라는 반환 타입만 바꾼 새로운 함수를 만들어서 진행하였습니다!  
- 또한 스텝 2와는 달리 `sorted()`도 넣어서 로또 번호들을 순서대로 정렬도 해보았습니다.  
- 스텝 3에서는 당첨번호 5개만 출력하라고 하였지만, 좀 더 넓게 사용하게 하기 위해 함수에 회차를 입력하면 입력한 값만큼의 회차수와 로또번호를 출력하도록 만들었습니다.  만약 입력한 회차보다 많거나 0을 집어넣으면 아직 추첨되지 않았다는 문구가 나오도록 하였습니다.  
- 스텝 2에서 헤맨 만큼 뭔가 스텝 3의 진행속도가 훨씬 빨라진거 같아서 기분이 좋네요🙂  
- 이번에도 피드백 잘 부탁드리겠습니다!
=> WEEK2[STEP3]김동용

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/LottoNumber.swift, CodeStarterCamp_Week2/main.swift
@uuu1101 안녕하세요 테테!
Step2 제출합니다!
숫자를 "[]" 안에서 빼고 출력하는데 애를 먹었네요 😆
=> Week2 [Step2] namukim

CodeStarterCamp_Week2/main.swift
@Babywalnut 
안녕하세요 바비님 
STEP 1 은 for문을 써서 코드를 짤 생각으로 순서도를 작성하였는데
막상 코드를 짜다보니 while문으로 짜야했습니다 ! 
for 문으로 1~6으로 하면 만약 겹치는 숫자가 나올 경우 추가를 안하고 넘어는 가지만 6개의 번호가 배열에 추가되지않습니다.
그래서 while문으로 count를 세어 겹치지 않게 6개가 추가될 때 까지 반복합니다 !
intersection을 사용하여 찍은 번호와 로또 당첨번호가 겹치는지 확인하였습니다
=> Week2 [STEP 2] iwon

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/main.swift, CodeStarterCamp_Week2/week2-step2.swift
@hrjy6278 
지스님 안녕하세요! week2-step3 과제 PR입니다.
makeLottoNumbers() 
: 로또 번호를 생성하는 함수입니다.
storeLottoRoundAndNumbers(in storage: inout [String: Set<Int>], _ round: Int, _ numbers: Set<Int>)
: 로또 회차와 번호들을 저장소에 저장하는 함수입니다.
findLottoNumbers(by round: String, in storage: [String: Set<Int>])
: n회차의 로또 번호들을 저장소에서 찾는 함수입니다.
changeLiterals(of integerNumbers: [Int])
: 정수들을 문자들로 변경하는 함수입니다.
printLottoResult(by round: String, in storage: [String: Set<Int>])
: n회차의 로또 결과를 출력하는 함수입니다.
질문
1. guard var 사용 하는지에 대한 고민
func printLottoResult(by round: String, in storage: [String: Set<Int>]) {
guard let lottoNumbers = findLottoNumbers(by: round, in: storage) else {
print("해당 회차에 로또번호가 없습니다!")
return
}
let sortedLottoNumbers = lottoNumbers.sorted()
let resultLottoNumbers = changeLiterals(of: …
=> Week2 [STEP 3] SEO-YJ

CodeStarterCamp_Week2/main.swift
@hrjy6278 
- STEP 1 에서 순서도를 먼저 작성해서 그런지 코드로 옮겨 작성할 때 막힘없이 쉽게 작성되어 놀라웠습니다.
- 겹치는 번호를 확인하기 위해 checkLottoNumber 함수를 생성 하고
lottoNumber와 myLottoNumber 교집합을 찾기 위한 intersection을 사용하였습니다.
또한 겹치는 번호가 있을 경우를 알기 위해 if 구문을 사용하고 intersection.count 가 0 보다 클 경우
겹치는 번호를 출력하고, 그렇지 않을 경우 겹치지 않는다는 멘트를 출력하도록 하였습니다.
- 한번의 명령만 입력하면 실행 될 수 있도록 playLotto 함수를 생성하였습니다.
- playLotto 함수에서 saveLottoNumber() 에 "Result of call to 'saveLottoNumber()' is unused"
라는 경고문구가 떠서 구글링을 해본 후 경고문구를 없애기 위한 @discardableResult 를 사용하였습니다.
- 궁금한 점 : 위 경우처럼 return을 하고 그 반환 값을 사용하지 않는다면 코드가 잘못 된 것인가요?
=> Week2 [STEP 2] yyjjgg

CodeStarterCamp_Week2/LottoNumber.swift, CodeStarterCamp_Week2/main.swift
@uuu1101 안녕하세요 테테!
월요일 시작입니다 ㅜㅜ 
드디어 2주차 마지막 스텝이네요 ㅠ
리뷰 부탁드립니다!
=> Week2 [STEP 3] namukim

CodeStarterCamp_Week2/lottoNumbers.swift, CodeStarterCamp_Week2/main.swift
@uuu1101  안녕하세요 태태! week2 step3입니다.
Dictionary에 대한 지식이 부족해서 공부하느라 조금 오래 걸렸네요..!
로또 번호를 생성하는 함수를 만들어서 저장하는 함수에 for-in문으로 반복하여 호출해주며 dictionary에 저장하였습니다.
그리고 출력할 회차를 매개변수로 받아서 해당 value의 요소들을 String으로 변환하여 저장하고, 받은 매개변수를 roundNumber변수에 저장하였습니다.
마지막으로 출력하는 함수에서 함수들을 호출하고 회차와 해당 로또 번호를 출력해주었습니다.
그리고 결과 저장한 각 회차들의 로또번호를 출력하는 코드도 추가하였습니다.
성공한 줄 알았는데 출력해보니까 모든 회차에 똑같은 숫자들이 들어있어서 뭔가 했는데, randomLottoNumbers를 전역 변수로 선언해줘서 그랬더라구요! 함수 내에 선언해줘서 해결하였습니다.
=> Week2 [STEP 3] uuuni

CodeStarterCamp_Week2/main.swift
@1Consumption 
순서도를 보면서 코드를 작성하는 과정에서 가장 먼저 막혔던 부분이 있었습니다. 바로 1 ~45 사이의 랜덤한 숫자를 생성하는 방법이었는데, 이것은 구글링을 통해 알아냈고 생각보다 간단하였습니다.
```Swift
var randomNumbers: Int = Int.random(in: 1...45)
```
이 방법을 통해 번호를 생성할 때 순서도에 맞게 while 을 사용하여 반복문을 만들어 주었습니다.
위 방법과 마찬가지로 **당첨 번호**도 랜덤으로 생성해주었습니다.
그 후, 겹치는 번호를 출력할 때 사용할 수 있도록 ‘**겹치는 로또번호**’에 해당하는 변수를 만들어 당첨 번호와 내 로또 번호를 비교해 겹치는 숫자를 담아주었습니다. 그리고 switch 구문을 사용해서 겹치는 숫자가 없을 경우와 있을 경우 각각의 문자열을 출력하도록 작성했습니다.
이렇게 코드를 작성하고 생각했던 점은, 
```Swift
print("축하합니다! 겹치는 번호는 \(correctNumbers) 입니다!")
```
이렇게 출력을 하게 되면 숫자가 대괄호에 감싸져서 나오게 됩니다. 하지만 보기에는 대괄호에 감싸져 있지 않았습니다. 
이 부분은 어떻게 보완할 수 있을지 고민해보려고 합니다!
=> Week2 [STEP 2] Dino

CodeStarterCamp_Week2/Week2Step02.swift, CodeStarterCamp_Week2/main.swift
@Babywalnut 
안녕하세요 바비님 !!
기존 코드에서 함수 하나 추가하는 거라 생각보다 빠르게 끝냈습니다 😄
처음에 난수 값이 매번 똑같은 게 나와 6회차까지 로또 번호가 똑같이 저장됐습니다.
함수를 여러번 호출하여도 같았습니다 ,, 새로운 랜덤 값으로 값이 덮어 씌워질 줄 알았는데 아니였습니다.
그래서 함수를 호출할 때 마다 이전의 값을 초기화를 해주고 랜덤 값을 넣었더니 해결됐습니다.
질문이 있습니다 !
1. checkNumber 함수를 Step03 에서 사용하지 않으면 Step03 코드를 올릴 땐 지우고 올려야 하는 건가요 ??  
2. 값이 바뀌질 않는 게 초기화 차이인가요 ..?!
=> Week2 [STEP 3] iwon

CodeStarterCamp_Week2/main.swift
@YebinKim 
week2 step2 내용입니다.
과제 출력을 위해 순서도에 없는 array를 추가사용하여 출력하도록 해보았습니다. 
저번 회의에서 알려주신 띄어쓰기나 네이밍 관련해서 좀더 신경 써 작성해보았습니다!
=> Week2 [STEP 2] themoon 

README.md
@ye-ha 
- 로또 당첨 번호 리스트에는 순서는 필요없고 겹치는 값이 없어야해서 Set 를 이용했습니다.
> (순서는 없고 고유한 값만 가진다.) 
라는 말을 적었는데, `Set` 변수를 선언한다는 말안에 포함되어있는 내용이라서 생략할까 하다가 일단 명확히 하는것도 괜찮을 것 같아서 넣었습니다. 예하 의견도 궁금합니다!
- 조건 부분에서 `randomInts` 에 랜덤 숫자를 6번 추가하지 않고 `randomInts.count` 가 6보다 작은지 확인한 이유는, `Set` 에 우연히 같은 숫자가 들어가면 저장된 값이 6개보다 작아질 수 있어서 총 갯수로 비교하는 코드를 생각했습니다.
=> Week2 [STEP 1] inho

README.md
@Jager-yoo 
1~45 사이의 수를 뽑는 방법은 1부터 시작하여 일정한 수를 더하거나 곱하는 등의 방법들이 무수히 많기 때문에 간단하게 나타내었습니다.
=> Week2 [Step1] BaDook2

CodeStarterCamp_Week2/main.swift
@leeari95 
func lottoNumberGenerator() -> [Int]
1. 생성된 로또 번호를 담을 Int 배열타입 변수를 선언합니다.
2. while 문을 이용하여 로또번호 배열 카운트가 6개보다 작으면  random 함수를 사용해 1~45사이 로또 번호를 생성하여 로또번호 배열에 추가합니다. 만약 중복된 번호면 로또번호 배열에 추가하지 않고 다시 로또 번호를 생성합니다.
3. 6개에 중복되지 않은 로또번호가 완성되면 리턴합니다.
func lottoNumberChecker(compare lottoNumber: [Int], with myLottoNumber: [Int])
로또번호 생성 함수에 의해 생성된 로또번호와 내 로또번호를 비교하여 맞은 번호를 출력해주는 함수를 만들었습니다.
로또 번호를 비교하여 맞은 번호를 체크한다는 의미로 함수 이름과 네이밍을 지었는데 의미가 잘 전달 될까요?ㅠ 영어가 짧아서 이름짓기 어렵습니다.ㅠㅠ
1. 함수 매개변수로 로또번호 배열과 내 로또번호 배열이 들어갑니다.
2. hitNumbers 라는 String 배열타입 변수를 만들어서 맞은 번호들을 저장했습니다. 원래는 Int 배열타입 변수로 만들었습니다. 그런데 맞은 번호를 출력하니 '축하합니다! 겹치는 번호는 [2 ,3 ,5] 입니다!' 이런형태로 번호가 대괄호 안에 출력되었습니다. 과제에서는 대괄호 없이 출력되야하기 떄문에 이 대괄호를 없애기 위해 고민을 많이했고 시간도 엄청 걸렸습니다.ㅠㅠㅠㅠ 고민한 결과 String 배열을 만들어서 맞은 숫자들은 String타입으로 변환하여 저장하였습니다. 그리고 이 …
=> Week2 [Step2] 둘리

README.md
@jaemuYeo 
잼킹! 안녕하세요~~
2주차 STEP1 PR요청 드립니다
로또 당첨번호 생성기 순서도 이미지 생성했습니다!
커밋을 두번 한 이유는 pr요청 직전에 생각해보니 과정을 조금 더 줄일 수 있을 것 같아 줄인 수정 입니다!😅
=> Week2 [STEP1] jeongmin(정민)

CodeStarterCamp_Week2/main.swift
@ye-ha 
- `createLottoNumbers` 함수는 순서도 흐름 그대로 구현했습니다.
- `checkWinning`의 함수 네이밍과 argument label을 신경썼습니다.
- `checkWinning` 함수 시작부분에 `let sortedLottoNumbers = lottoNumbers.sorted()` 를 실행한 이유는 나중에 결과값에서 당첨된 숫자들이 오름차순으로 보이게 하기 위함입니다. (Set 는 순서가 없는 컬렉션이므로)
- 21번 코드에서 `sameNumbers` 를 문자열 타입으로 선언한 이유는 출력과 연관되어있습니다! (뒤에 적어두었습니당)
- `checkWinning` 함수의 반복문 부분을 처음 작성했을 때는
```
for lottoNumber in sortedLottoNumbers {
for myNumber in myNumbers {
if myNumber == lottoNumber {
sameNumbers.append(String(lottoNumber))
}
}
}
```
이런 식으로 작성을 했는데, 배열의 `contain`메서드를 이용하면 더 간결하고 직관적으로 이해할 수 있어서 수정했습니다. (`filter` 라는 메서드를 이용하면 더 간결해 질것 같은데 클로저 부분이 아직 미숙해서 두었습니다.)
- 비슷하게 겹치는 번호를 찾는 조건문에서도 `isEmpty` 를 이용하였습니다. (배열의 기능 활용..?)
- 마지막으로 제일 고민했던😵‍💫 ,, 배열의 원소를 대괄호 없이 출력하기 위해 여러가지 시도 끝에 결국 `sameNumbers.joined(separator: ", …
=> Week2 [STEP 2] inho

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/main.swift
@leeari95 
func storeLotto() -> [String : [Int]]
step2 에서 만든 로또번호 생성하는 함수를 실행하여 회차(key)와 이에 따른 로또 번호(value)를 딕셔너리에 저장합니다. 함수를 5번 실행하여 총 5회차 로또번호가 저장되게 하였습니다.
func showLotto(of round: String, from lottoHistory: [String : [Int]])
딕셔너리 key로 사용할 round와 위 storeLotto() 함수로 만든 회차와 로또번호가 저장된 딕셔너리가 매개변수로 들어갑니다.
딕셔너리["2회차"] 를 그대로 프린트하면 2회차의 옵셔널 인트 배열타입의 로또 번호가 출력됩니다.
옵셔널 값을 인트 배열로 가져오기 위해 let if 를 사용하였고, 배열값이 아닌 각 숫자 값을 가져와서 출력하는 것은  step2에서 맞은 로또번호 출력하는 함수와 동일하게 구현했습니다.
step2 보다 큰 어려움은 없었는데 옵셔널 개념이 좀 어려운 것 같습니다ㅎㅎ 이번주 안에는 꼭 이해할 수 있었으면 좋겠습니다~
=> Week2 [Step 3] 둘리

CodeStarterCamp_Week2/main.swift
@yim2627
안녕하세요!.
Week step2 PR 드립니다.
confirmLottoNumbers 함수는 원래 이중 for문을 돌면서 확인하는 방식의
for i in myLottoNums {
for j in createLottoNums {
if i == j {
winNumbers.append(i)
continue
}
}
}
이런 형태였는데
클로저란걸 알게되어서 적용해봤습니다. 아직 클로저는 익숙치가 않네요.;.
그리고 createLottoNumbers 함수에도 클로저를 적용하고 싶은데 잘 안되어서 일단 while문을 통한 형태로 작성하였습니다.
=> Week2 [Step2] rimeorange

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/lotto645.swift, CodeStarterCamp_Week2/main.swift
@yim2627 
순서도에 맞춰서 로또번호를 생성하는 코드를 작성한 뒤
생성된 로또번호와 내가 적어낸 번호를 맞춰서 상황에 따른 결과를 출력해주는 코드를 작성했습니다.
=> Week2 [STEP 2] suyeon

CodeStarterCamp_Week2/main.swift, README.md
@jaemuYeo 
잼킹! 안녕하세요! 😊
2주차 스텝2 PR요청 드립니다
순서도의 수정이 조금 있었고
당첨번호와 찍은번호를 확인하는 함수의 네이밍과 인자레이블 네이밍,
반복문의 변수 이름에 대해서 number라는 이름보다 좋은 이름은 없을지,
맞춘 번호를 출력하는 부분에서 좀 더 간단하고 명확한 방법이 없을까 고민 했습니다.
저로서는 최대한 명확하고 간단하도록 짜봤는데 더 좋은 방법이 있지 않았을까 궁금합니다! 🤔
=> Week2 [STEP2] jeongmin(정민)

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/MyLottoNumber.swift, CodeStarterCamp_Week2/WinningLottoNumberAllRound.swift
@llghdud921 
안녕하세요 제리!
Mission2 의 마지막 Step3를 작성했습니다.
-  getWinningLottoNumberAllRound 함수에 지역 변수로 선언하고, 사용할때는 return 값에 담아서 사용할수 있게 만들었습니다!
- extractNRoundLottoNumber의 반환값으로 특정 회차의 당첨 번호를 알수 있게 했습니다.
- map + joined 내장 함수를 통해 String을 바로 출력할수 있게 구성했습니다.
감사합니다!
=> Mission2: Step3: 로또 당첨 번호를 회차별로 저장하고, 확인하자!

CodeStarterCamp_Week2/main.swift
step3 pr 요청드립니다!
@yim2627
createLottoNumbers 함수가 호출 될때 생성된 로또번호를
saveRoundLottoNumbers 에 prameter로 전달하여 회차별로 저장되는 
함수를 만들었습니다.
=> Week2 [STEP 3] rimeorange

CodeStarterCamp_Week2/main.swift
@July911 
[STEP2]
- Array 보다는 자주 사용하지 않은 Set로 사용해서 번호 생성
[STEP3]
- savingLottoNumbers 함수를 만들어 딕셔너리에 로또 회차별 번호 저장
- 실행코드 및, set를 array로 변환해서 오름차순으로 정렬
- 초기화 함수를 만들지 않아 처음에 오류를 잡지 못했지만 전역변수를 초기화 하지않아 배열이 쌓여만 가는 오류 해결
- count 변수를 생성해서 딕셔너리의 key로 사용했음.
=> Week2 [STEP 2,3] beam2

CodeStarterCamp_Week2/LottoMaking.swift
@llghdud921  안녕하세요 제리
Week2 [step2] 입니다.
이번 step2는 Int형에서 String으로 배열 변환하는 것에 어려워서 인터넷을 찾아보고 해결했습니다.
=> Week2 [step2] duck

CodeStarterCamp_Week2/STEP2.swift, CodeStarterCamp_Week2/STEP3.swift, CodeStarterCamp_Week2/main.swift
STEP1 에서 작성한 순서도를 기반으로 하여 추출한 번호를 저장할 set형 변수  lottoSet을 선언하고 
while문과 count 메소드를 사용해서 lottoSet의 요소가 6개가 될 때 까지 번호를 생성하고 lottoSet에 삽입하는 과정을 반복하여 당첨번호가 6개만 추출 되도록 하였습니다.
```swift
var coordinate: Set<Int> = Set<Int> ()
var count: Int = 0
```
- myLottoNumbers와 lottoSet 에서 일치하는 숫자들을 저장하기위해 coordinate 변수 선언.
- 번호 사이에 콤마를 찍을때 예외 처리를 위해 count 변수 선언.
```swift
for tofind in myLottoNumbers {
for lotto in lottoSet {
if tofind == lotto {
coordinate.insert(tofind)
}
}
}
```
- 2중 for ... in 문을 사용하여 순회하면서 같은 숫자를 발견하면 coordinate변수에 insert메소드를 통해 삽입함.
```swift
if coordinate.count == 0 {
print("아쉽지만 겹치는 번호가 없습니다.")
return
}
```
- 겹치는 숫자가 없는 경우 count 메소드를 사용하여 갯수를 측정한 후 0 이라면 문장을 출력한뒤 return을 통해 함수 종료.
```swift
print("축하합니다! 겹치는 번호는 ",terminator: "")
for same in coordinate {
count += 1 …
```
=> Week2 [STEP2] much3m

CodeStarterCamp_Week2/main.swift
@ye-ha 
- 11번 코드에 회차를 담기 위한 변수를 선언했습니다.
- 12번 코드에 회차와 로또 당첨번호를 담을 빈 Dictionary 를 선언했습니다.
- `createLottoNumbers` 함수를 실행할때마다 이전 회차에 +1 을 하고, 새로 만든 `storeLottoNumberList` 함수를 호출합니다.
- 로또를 생성할 때 회차가 증가하는걸 감안해서 Dictionary에 키값을 추가할 때 문자열 보간법을 이용했습니다.
- 오름차순으로 정렬된 결과를 출력하기 위해 미리 `lottoNumbers.sorted()` 해주었습니다.
- 회차를 정수타입 매개변수로 받아서 원하는 회차의 로또번호를 출력하도록 구현했습니다.
- Dictionary에서 값을 안전하게 가져오기 위해 `if let` 옵셔널 바인딩을 이용했습니다.
- print의 결과롤 배열을 출력할 때 대괄호 없이 원소만 출력하기 위해 우선 map을 이용해서 정수 타입 배열을 문자열 배열로 바꾸고,
그 문자열 배열에 joined 메서드를 적용했습니다.
- 회차 범위 밖의 숫자를 입력했을 때 출력될 메세지를 추가했습니다.
- 로또 번호를 여러번 생성할 때 함수를 이용하면 편리할것 같아서 반복할 횟수를 매개변수로 받는 함수를 만들었습니다.
- 반복문 내부에서는 로또 번호를 생성하고, 내 번호와 비교하고, 결과를 보여주는 함수들을 호출합니다.
---
- 모든 함수에서 함수의 역할을 알 수 있도록 네이밍과 argument label을 정했습니다.
- 이전 PR에서 `checkWinning` 네이밍에 명사가 붙는 아이디어를 주셔서 생각해봤는데, …
=> Week2 [STEP 3] inho

CodeStarterCamp_Week2/main.swift
@leeari95 
안녕하세요!! Step2 PR 드립니다!!😆
=> Week2 [Step2] Lily

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/Lottery.swift, CodeStarterCamp_Week2/main.swift
@ye-ha 
- 이번 과제에서는 순서도에 맞게 함수 만들기, 하나의 함수가 하나의 역할을 하기 이 두가지를 중점적으로 생각하며 과제를 진행하였습니다.
- 전역변수 보다는 지역변수를 사용하는것을 주 목표로 작업하였습니다.
- 실제 이런 앱을 협업하며 만든다고 생각하고 작업을 해보았습니다. '내 로또 번호'에서 문제가 좀 있었는데 앱이라면 사용자가 입력 한 값이 이 변수로 들어올텐데, 아직 이부분은 당연히 모르는 부분인지라.. 일단 상수에 제가 직접 입력하는 방식을 사용자가 입력한다라고 생각하고 상수 하나를 전역으로 선언했습니다. 과제에도 그렇게 선언하라고 했구요..!
- 사실 상상도 못한 부분이었습니다. 겹치는 번호를 `a, b, c, ...` 이런식으로 표현해야 했습니다. 문제는 겹치는 번호가 반드시 6개가 아니라는 점이었습니다. 
- 처음에는 *'이거 그냥 separator 쓰면 해결되는 문제 아니야?'* 라고 생각했죠.
```Swift
print(sortedComparedNumbers[0], sortedComparedNumbers[1], sortedComparedNumbers[2], sortedComparedNumbers[3], sortedComparedNumbers[4], sortedComparedNumbers[5], separator: ", ")
``` 
- 하지만 이렇게 함수를 사용하니, 너무 길어지는데다가 겹치는 번호의 갯수가 정해지지 않아서 1등 당첨이 아닌이상 런타임 오류가 생기는 치명적인 결함이 있었습니다.
- 그렇다고 switch문을 사용해서 각 배열의 데이터 갯수에 따라 다르게 설정하는 …
=> Week2 [STEP 2] wonbi

CodeStarterCamp_Week2/main.swift, README.md
@oksunwoo 
* "1회차": [1, 2, 3, 4, 5, 6]와 같은 Key와 Value를 가집니다.
```swift
var pastWinningLotteries = [String: [Int]]()
```
위 코드는 Dictionary타입의 컬렉션의 변수를 pastWinningLotteries즉 지나간당첨복권들로 Naming하였습니다.
* 새로운 로또 당첨 번호를 생성하면, 직전 회차에 1을 더해 금번 회차를 만들어냅니다.
* 회차를 Key로, 새로운 로또 당첨 번호를 Value로 하는 Dictionary에 저장합니다.
```swift
func appendWinngLottery(to pastWinningLotteries: inout [String: [Int]], by key: String, and value: [Int]) {
pastWinningLotteries[key] = value
}
```
우선 appendWinningLottery to pastWinningLotteries by key and value로 Naming한 함수입니다. 즉 당첨복권을 지나간 당첨 복권들에 키와 값으로 첨부한다라는 의미를 가지고 있습니다. 해당 함수는 전달받은 pastWiiningLotteries의 주소값에 해당하는 Dictionary컬렉션에 전달 받은 Key로 Value값을 추가합니다.
또한 요구사항인 새로운 로또 번호를 생성하고 해당 회차의 로또 번호를 Dictionary에 저장하는 기능을 추가하기위해 이전에 작성한 generateWinningLottery함수에 코드를 추가적으로 아래와 같이 작성하였습니다. …
=> Week2 [Step 3] Onestar

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/Week2Step2.swift, CodeStarterCamp_Week2/main.swift
안녕하세요 제인님! @siwonkim0 
미션2 내 번호와 맞추어보기! PR 드립니다.
일단은 최대한 미션의 지문대로 코드를 짜봤는데 만약 내가 숫자를 직접 고를 수 있다면, 겹치는 숫자를 보여주는 함수를 호출 시 매개변수로 내가 고른 숫자를 입력하면 좀 더 재미있는 프로그램이 되지 않을까 하는 생각이 들었습니다.
두 개의 함수로 끝낼 수 있었지만 교집합을 체크하는 함수가 자칫 무거워질 수 있을 것도 같아 기능을 나누어 세 개의 함수로 작업했습니다. (지금 같은 단순한 작업에서 무슨 의미가 있겠냐 하는 생각이 들긴 했습니다.ㅎㅎ)
- 어려운 점
1. 변수/함수명을 정하는게 어려웠습니다...
- 아쉬운 점
1. 미션 지문처럼 겹치는 번호를 포함하는 문구를 print 할 때 대괄호가 없이 출력이 되게끔 하고 싶었는데 방법을 모르겠습니다... (set를 벗기고 int값만 출력하게 하면 될 거 같은데 좀 더 고민해봐야할 것 같습니다.)
2. 미션 지문에서는 내가 고른 번호를 변수로 정의하라고 했는데 값이 바뀌지 않기 때문에 상수로 정의한 부분이 있었습니다....
3. 파이썬에서는 난수를 뽑을 때 여러개를 동시에 뽑을 수 있는 메소드가 있었는데 스위프트는 반복문으로 여러개를 뽑아야 해서 아쉬웠습니다...
4. 생각보다 겹치는 숫자가 너무 안 떠서 코드에 문제가 있나 싶었습니다...(그냥 딴소리 입니다)
- 재밌었던 점
1. 다른 언어를 배울 때는 거의 배열이나 딕셔너리 위주로만 써봤지 집합을 쓸 기회가 없었는데 이번 미션에서 집합을 주제로 코딩할 수 있어서 재미있었습니다!
코멘트와 피드백 부탁드립니다!! …
=> Week2 [Step2] keyster

CodeStarterCamp_Week2/Method.swift, CodeStarterCamp_Week2/main.swift, README.md
=> Week2 [Step3] BaDook2

CodeStarterCamp_Week2/LottoRound.swift
@llghdud921 안녕하세요 제리
step3입니다.
이번 스텝은 저한테 어렵게 다가 왔어요ㅠ
딕셔너리 키값을 정렬하다가 키를 배열로 받고 하다가 안되고 String으로 받으려다 안되서 결국 Int로 받고 겨우 정렬 했네요...
옵셔널에 대해서도 더 많이 공부를 해야겠다는 생각이 드는 미션이었습니다.
=> Week2 [step3] duck

CodeStarterCamp_Week2/main.swift
@oksunwoo 
---
```swift
func makeLottoNumbersFor(times numbers: Int) {
if numbers >= 1 {
for number in 1...numbers {
var newLottoNumbers: [Int] = []
newLottoNumbers = pickLottoNumbers()
lottoNumbersDictionary["\(number)회차"] = newLottoNumbers
}
} else {
print("생성하고자 하는 로또 당첨 횟수는 1보다 크거나 같아야합니다.")
}
}
```
+ 사용자가 혹시나 양수가 아닌 값을 매개변수로 넣었을 때 생길 수 있는 오류를 If문을 통해 해결하였습니다.
+ 해당 횟수만큼, step2에서 작성했던 pickLottoNumbers라는 메소드를 통해 정수값을 Array에 담습니다. -> 전역변수로 생성한 lottoNumbersDictionary에 키와 밸류값으로 넣어 담습니다.
```swift
func showLottoNumbersAt(order number: Int) {
if number >= 1 && number <= lottoNumbersDictionary.count {
if let numbers = lottoNumbersDictionary["\(number)회차"] {
var arrayForShowingNumbers: [Int] = [ ]
arrayForShowingNumbers = numbers
let findingNumbersStringArray = convertStringArray(from: …
```
=> [Week2] Step3 윤세영

CodeStarterCamp_Week2/main.swift
@yaewonLee 
안녕하세요, 샬롯^^
드디어 스텝3입니다..!!
이번에 추가된 함수는 아래 2가지 기능을 포함하고 있습니다.
- 로또를 원하는 회차 만큼 돌린다.
- 돌릴 때 마다 회차에 저장한다.
=> Week2 [STEP 3] Jessi

CodeStarterCamp_Week2/main.swift
@Allie-e 
앨리 안녕하세요! week2 [step2] 미션을 완료했습니다 :)
week2의 step1 미션 순서도에서 로또 번호를 뽑는 함수를 만들 때,
`var random = Int.random(in: 0...46)`이라는 변수를 따로 선언한 후에 
`lottoNumbers.insert(random)` 
이런식으로 Set에 추가하도록 구성을 했었는데,
이번에 코드를 짜면서 random 변수를 따로 선언하지 않고,
`lottoNumbers.insert(Int.random(in: 0...46))` 
이렇게 코드를 작성하는게 간편할것 같아 순서도 내용과 다르게 진행했습니다!
참고해주시면 감사하겠습니다 :)
그리고 코드를 작성하면서 궁금한 점 / 어려웠던 점이 있어서 질문 드립니다!
임의의 변수 Set 타입을 출력한다고 할 때, `print(set)`의 결과 값은 `[ ]`에 담겨서 출력이 됩니다.
`[ ]`을 빼고 출력하고 싶을 땐, for-in 문을 이용하여, 
```swift
for num in set {
print(num)
}
```
이런 식으로 출력해야한다고 배웠습니다.
하지만 이번 미션을 수행하다보니, 제 코드에서 ⬇️
```swift
case 1:
print("축하합니다! 겹치는 번호는", terminator: " ")
for num in intersection {
print(num, terminator: " ")
}
print("입니다!")
```
case 1인 경우 즉, intersection의 멤버 개수가 1인 경우에, 
하나의 인자를 출력하는데도 for문을 돌려야하는게 코드도 길어지고 …
=> WEEK2 [STEP2] dorii

CodeStarterCamp_Week2/main.swift, CodeStarterCamp_Week2/step2.swift
@eunseo5355 
안녕하세요~! STEP 2 리뷰 요청드립니다!
과제의 지시사항에는 없었으나, 함수가 제대로 작동하는지 알아보기 위해 `당첨 번호`와 `찍은 번호`를 출력하는 함수를 함께 기재하였습니다.
그리고.. 제가 실수로 main 브랜치에 PR을 보내서 해당 PR을 close하고 다시 PR 보내는데 요렇게 하면 될까요..?
죄송합니다ㅠㅠ
=> Week2 [STEP 2] summer

CodeStarterCamp_Week2/main.swift
@jaemuYeo 
Set의 함수 intersection을 이용하여 로또당첨번호와 myLottoNumbers의 중복되는 부분만 추출했습니다.
Set의 값들을 괄호([])가 없는 1줄의 문자열로 표현하고싶어서 이것저것 찾아봤는 데요.
문자열 배열을 1줄의 문자열로 바꿔주는 joined라는 함수가 있다는 것을 알게 되었습니다.
다만, intersection Set을 문자열 배열로 바꿔주는 작업이 필요해서 
고차함수 map을 이용하여 문자열 배열로 바꿔주었습니다.
print문을 사용하여 출력할 때, 문자열을 넣어서 그대로 출력하기보다는
재사용할 수 있는 변수 resultOfLotto를 이용하여 출력하였습니다!
=> Week2 [Step 02] Oh Sung Ah

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/main.swift, CodeStarterCamp_Week2/step2.swift, CodeStarterCamp_Week2/step3.swift
@eunseo5355 안녕하세요~ Week2 STEP 3 리뷰 요청드립니다!
DM으로 문의 드렸던 같은 로또 당첨 번호를 반복해서 뱉어내는 문제 말고는 이번주는 큰 문제 없이 진행되었습니다 =)
개념적으로 이해할 수 있게 짚어 주셔서 정말 감사합니다!
=> Week2 [STEP 3] summer

CodeStarterCamp_Week2/main.swift
@jaemuYeo 
안녕하세요 잼킹! 잼킹이 주신 힌트 덕분에 해결하고 왔답니다. :) 
사실 어제 joined(separator: )이걸 보긴 했는데..., 제가 계속 새로운 변수(상수)를 선언해주지 않아서 작동하지 않았던 거라는 걸 깨달았습니다! 
어제 스터디에서 String 타입으로 바꿔보라는 힌트를 듣고 
혼자 해결해보려고 했는데 역시...👍 
잼킹과 다른 분들의 도움이 최고인 것 같습니다.👍
띄어쓰기나 문법 최대한 신경써봤는데 이번엔 잘 했는지 모르겠네요🤔
=> Week2 [Step 2] OneE

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/generateLottoNumber.swift.swift, CodeStarterCamp_Week2/main.swift
안녕하세요 호댕! (@yanghojoon)
Week2의 STEP2를 작성하게되어 PR 보내드립니다.
이번 스텝은 아래와 같이 구성해봤습니다.
1. 기존에 작성했던 순서도와 동일하게 로또번호를 생성하는 함수
2. 당첨 번호와 내 번호를 대조해본 결과를 출력하는 함수
2번 함수는 당첨 번호가 내 번호를 포함하고 있으면 멤버가 append 되는 Array 타입의 변수(matchedNumbers)를 선언해서 확인하는 방식으로 작성해봤습니다.
처음에는 이 배열을 그대로 결과값으로 출력하려고 했는데, 배열이다보니 미션에서 요구한 것과는 다르게 대괄호가 포함되어서 출력이 되더라구요😓
그래서 switch문을 이용해서 matchedNumbers.count 값에 따라 코드를 따로 작성해서 당첨이 되었을 때와 안 되었을 때를 조금 더 명확하게 구분짓는 방식으로 작성하고 -> 당첨번호가 2개 이상일 때 괄호 없이 출력되도록 인덱스 값을 가져와 출력해봤습니다.
#
추가로 코드를 작성하면서 궁금한 점이 있어 질문드립니다!
1번 함수에서 당첨 번호를 .ramdomElement() 메서드를 사용해서 가져오게 되면 옵셔널 타입으로 값을 가져오게 돼서 nil일 때를 대비해 default 값을 작성해야 하는 것으로 보였습니다.
현재 작성한 함수는 nil이 있을 수 없으니 default값으로 일단 0이라는 숫자를 임의로 기재하였는데, 이렇게 작성해도 되는 걸까요? 혹시 조금 더 안전한 코드를 위해서 생각해 보아야 할 부분이 있는지 궁금합니다!
=>  Week2 [STEP 2] 애쉬

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/Step 2.swift, CodeStarterCamp_Week2/Step 3.swift, CodeStarterCamp_Week2/main.swift
@ye-ha 
- 이 문제에서도 전역변수를 하나 추가 했습니다. 
> 회차와 Lotto번호들을 저장하는 Dictionary 타입의 변수를 생성합니다.
- 이 `로또 번호를 저장하는 변수`인데요. 이걸 전역 변수로 설정한 이유는, 각 함수 내부에 지역변수로 이를 할당하면 각 함수가 실행될 때마다 각각 다른 값을 가지는 딕셔너리가 만들어지기 때문이었습니다.
- 예를 들어, `로또 번호를 만드는 함수`, `당첨 로또 번호를 확인하는 함수` 안에 지역변수로 들어가 있으면, 각 함수 안에 당첨 로또번호가 따로 존재하게 되는 결과가 생겼기 때문입니다.
- 사실, `로또 번호를 만드는 함수`의 반환 값을 딕셔너리로 한 다음, 이 함수를 `당첨 로또 번호를 확인하는 함수`의 매개변수로 넣을까 생각도 했었는데요. 
```Swift
checkWinnerNumbers(storage: makeWinnerNumbers(time: 5), round: 2)
```
- 위와 같은 느낌으로 말이죠. 근데 이건 가독성도 안좋고, 실행할 때마다 `로또 번호를 저장하는 변수`를 자꾸 초기화 시키는 문제가 있었습니다.
```Swift
checkWinnerNumbers(storage: makeWinnerNumbers(time: 5), round: 2)    // 
checkWinnerNumbers(storage: makeWinnerNumbers(time: 5), round: 2)    // 윗줄의 결과와 다른 값이 나옴
checkWinnerNumbers(storage: makeWinnerNumbers(time: 5), round: 4)    // …
```
=> Week2 [STEP 3] wonbi

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/main.swift, CodeStarterCamp_Week2/step2_lotto.swift
　 
@forestjae 안녕하세요 숲재!
완성은 금요일 초저녁에 했는데 이것저것 도전해보다가 이제야 제출합니다ㅜㅜㅜ
`체크 없는 체크박스`가 질문사항입니다. 분리하기 어려워서 묶어 쓰는 대신 따로 표시했습니다😅
　 
- `repeat ... while`문: 선실행 후조건확인
↳ `<=7`이 아니라 `<6` → 코드상에 꼭 숫자 6으로 쓰고 싶어서 선택했습니다!
- `.random`으로 무작위 숫자 추출: `.shuffled`와 고민
↳ 기존 순서도나 미션 목적에 부합하는 건 `.random`쪽인 것 같아 선택
↳ `.shuffled`의 경우 코드가 간결하지만 타 변수와의 콜렉션타입 호환문제가 있었음
- 나만의 번호를 '변수'로 할당하라는 조건이 왜 있는지 생각했습니다.
- 함수 내 변수의 기본값 개념을 활용해보라는 뜻인가? (& 콜렉션타입을 입력값으로 받는 법을 연구해보라는 건가)
- 혹시 다음 스텝에서 재사용할 일이 있는 코드인가?
- 결론적으로는 혼자 함수화하라는 지시가 없는 점, 미션 요구조건 흐름대로 구현되게만 하면 될 거란 점을 근거로 전역변수로 작성했습니다.
- `if ... if else`문: 이번에 배운 `switch case`문을 쓰고 싶었지만 후술한 변수 타입 문제로 비교값 선정에 어려움을 겪어 포기
- 연산자`!=`보다 확실한 `.isEmpty` 사용
　 
- 결과 출력부를 별도이 함수로 선언하고 싶었지만
저번 미션 때처럼 상수·변수 범위 문제에서 막혀서 + 아래 2번 탓에 이미 늘어진 코드가 더 길어질까봐
결과 확인부와 합쳤습니다.
- 가장 오래 고민한 파트입니다.
아래 언급한 구글링 …
=> Week2 [Step 2] Junely

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/main.swift, CodeStarterCamp_Week2/step2.swift, CodeStarterCamp_Week2/step3.swift
@yim2627 
week2 [step3] 로또번호 불러오기 입니다
=> Week2 [STEP 3] suyeon

CodeStarterCamp_Week2/main.swift
@Allie-e님  안녕하세요 ☺️
벌써..5월이에요!!
2주차 step3올리겠습니다!
=> WEEK2 [STEP3] bangwoo

CodeStarterCamp_Week2/main.swift
@jaemuYeo 
잼킹! Step3를 (미)완성해왔습니다. 🤔
하나 의문인건 사실 아직 옵셔널에 대한 개념이 거의 없어서 이렇게 쓰는게 맞나? 하는 걱정이 좀 드네요... 🤔
그리고 아직 미완성이라고 한 이유는 딕셔너리를 출력할 때, 1회차, 2회차, 3회차 등등 이렇게 라운드가 늘어나면 늘어나는대로 순차적으로 출력이 되도록 만들고 싶은데 그렇게 하려면 .sorted()를 사용해야하는 것 같은데, .sorted(separated: "\(round)")로 하니까... 오류가 발생하더라구요... ;ㅅ; 그래서 구글링 한 결과인 > 와 같은 등호? 를 사용해서 해봤는데 그것도... 사용되지 않는다는 노란 줄이 나타나서 🤔 대체 어떻게해야 하는지 잘 모르겠는 상태랍니다... 
혹시 해결할 수 있는 방법이 있을까요? 🤔
=> Week2 [Step 03] OneE

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/lottery.swift, CodeStarterCamp_Week2/main.swift
=> Week2 [STEP 2] 우디

CodeStarterCamp_Week2/main.swift
안녕하세요!
Step 2를 진행하고 PR 생성합니다.
이번 과제에서 생각이랑 좀 달랐던 게 있었습니다.
1. Set 안에는 중복된 값이 저장이 안된다는 사실을 처음에 몰라서 중복 값을 추려내야 할 거라고 생각했는데, 그렇지 않아서 갯수만 확인하면 됐고...
2. Step 2 미션에서 `let myLottoNumbers: [Int] = [1, 2, 3, 4, 5, 6]` 과 Set으로 만들어진 로또 번호를 비교해야 한다고 해서 Array와 Set을 어떻게 비교해야 하지 하고 하나씩 비교하는 반복문들을 만드는 방법을 생각했는데, 의외로 Set과 Array 간 교집합 연산이 바로 돼서 정말 신기했습니다.
한번 확인 부탁드릴게요 @July911 감사합니다 :)
=> Week2 [STEP2] Ohseyong

main.swift
@forestjae 안녕하세요!!
Week2 [STEP 2] 입니다.
=> Week2 [Step 2] bingo(어송)

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/generateLottoNumber.swift, CodeStarterCamp_Week2/main.swift
안녕하세요 호댕, (@yanghojoon)
Week2 STEP3 PR 보내드립니다!
이번 스텝에서는 추천해주신대로 최대한 전역변수를 쓰지 않고, 지역변수를 써서 진행을 해보려고 했습니다만... 
기존에 만들어둔 당첨번호-내 번호를 대조해보는 함수와 당첨 결과를 출력하는 함수에서 전부 winningNumbers 변수를 사용하고 있어서 결국 다시 전역변수로 사용하게 되었습니다. 🥲
이번 스텝에서 요구하는 기능만 해도 된다면 winningNumbers 변수를 generateLottoNumbers() 함수에서 saveLottoResult() 함수에 매개변수로 넘기는 방법으로는 가능할 것 같았습니다!
DM으로 질문드렸던 내용(generateLottoNumber()를 반복 호출해도 같은 번호만 나왔던 것)과 연관되는 점이 있는데요.
전역변수로 선언된 Set이나 Dictionary 타입의 변수는 함수가 호출될 때도 값이 초기화 되지 않고, 이미 저장된 값이 잘 나오는 것 같았습니다.
그런데, 지금은 지역변수로 있는 29번 줄 상수 round를 전역변수로 선언하고 saveLottoResult()-printLottoHistory()를 호출했을 때, 결과가 1회차만 나오는 것으로 보아 계속 0으로 초기화되는 것 같았습니다.
혹시 타입별로 값이 초기화가 되고, 안 되는 차이가 있는 이유가 있을까요?
(아니면 코드의 문제일까요....?...😵)
=> Week2 [STEP3] 애쉬

CodeStarterCamp_Week2/lottery.swift, CodeStarterCamp_Week2/main.swift
@yim2627 옵셔널이 너무 생소해서 뇌가 녹아버릴뻔 했지만 어찌저찌 완성은 해보았습니다 ㅎㅎ;;
=> Week2 [STEP 3] 우디

CodeStarterCamp_Week2/main.swift
@leeari95 
안녕하세요!! 너무 오랜만에 PR 드리네용.. Step3를 하면서 궁금한 점이 몇가지가 있어 질문도 함께 드립니닷!
1. 모든 변수나 상수에는 nil을 저장할 수 없나요?
2. nil을 저장하고 싶다면 옵셔널로 감싸주어야 nil을 저장할 수 있는건가요?
3. 옵셔널 바인딩을 통해 벗겨낸 값에는 절대 nil이 있을 수 없다고 생각하면 되는건가요?
4. 
```
let x : Int? = 10
if let xx = x {
print(“x = \(xx)”)
} else {
print(‘x is Optional”)
}
```
과 같은 코드는 ```xx```라는 값이 변하지 않는(let)상수에 ```x```라는 옵셔널을 벗겨 줄 값을 대입하고 벗겨졌다면 ```print(“x = \(xx)”)``` 문을 실행하고 아니라면 ```print(“x is Optional”)```을 출력한다. 라고 해석하면 될까요?
5. 이때 그러면 만약 옵셔널이 아닌값을 옵셔널로 벗겨준다면 (```let x: Int = 10``` 이라는 상태라면) 옵셔널만 옵셔널 바인등을 할 수 있다고 오류가 나는데, 이런 과정을 통해 ```x```라는 값이 옵셔널인지 아닌지 확인하는 용도로 사용하는 경우도 있을까요?
6. 위 코드에서 else문이 없어도 정상적으로 작동을 하는데 else 문으로 갈 수 밖에 없는 상황을 모르겠습니다 ㅠㅠ..
7. 20번째 줄에서 저는 2회차라는 String을 사용해서 해보았는데.. 이 값을 따로 변수에 적어서 "2회차"보다 변수를  넣어주는게 더 좋을까요?
옵셔널이 너무 이해가 안가서 질문을 많이 …
=> Week2 [STEP3] Lily

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/Step3.swift, CodeStarterCamp_Week2/main.swift
=> Week2 [Step3] 을생

CodeStarterCamp_Week2/main.swift
@llghdud921 
안녕하세요, 제리!
이번 순서도를 작성하면서.. 구글링으로 이래저래 만들어서 돌아가긴 하지만 제가 내부를 이해하고 코드를 짠 것 같지 않아서 찝찝합니다 :(
처음 배우는거라 지금은 단순 구현에 만족해야겠죠..?
항상 딥하게 코멘트 해주셔서 감사해요! :)
=> Week2 [STEP2] piuri

CodeStarterCamp_Week2/main.swift
@leeari95 
안녕하세요 아리님 ! Step2 진행 완료 하여서 PR 드렸습니다.
우선 이번 Step은 전체적으로 생각할게 너무 많았던거 같아서 감조차도 잡히지 않아서 DM도 드렸었던것 같아요 !!
그래도 말씀해주신거 토대로 코드작성 한번 진행 해봤습니다 :) 그리고 .. 커밋 단위를 쪼개서 진행하는게 아직 습관이 되지 않아서
마지막 코드 다 작성하고 Push했을때 깨달았습니다..ㅠㅠ ... 단위를 쪼개지 않았다는걸... 조금더 신경써서 노력 해보겠습니다!
이번Step도 잘 봐주세요 :) 감사합니다!
=> Week2 [STEP 2] 임덤덤

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/main.swift, CodeStarterCamp_Week2/step2_lotto.swift, CodeStarterCamp_Week2/step3_lotto.swift
@forestjae 안녕하세요 숲재! 스텝3 PR 올립니다 🙂
코드에 바로 코멘트 남겼습니다!
3가지 방식으로 구현했습니다.
- **커밋메시지에 '회차마다 0으로 초기화'라는 말이 들어간 것**: 
Run(실행)을 누를 때마다 로또 이력을 저장하는 Dictionary변수의 값이 초기화되지 않고 누적되어야 하는 줄 알고, 일단 기초적인 것만 구현해보자는 생각으로 commit한 분량입니다.
- **Step2파일도 같이 커밋된 것**: 
step2 때 실현부(main)에 있던 걸 일부 삭제/이동했습니다.
- enum의 원시값(1부터 시작하도록), 그 안에 메서드를 넣을 수 있다는 점을 활용해 n회차의 n을 걸러내는 작업을 건너뛸 생각을 막연히 해봤지만, enum의 case에는 nil이 올 수 없음을 알고 보류했습니다.
대신 **switch case구문의 case에 nil을 배정**할 수 있었습니다.  옵셔널 및 가독성 문제로 별도의 상수를 만들었습니다.
\+ **'특정 회차의 value값'을 나타내는 상수 이름**을 복수형(`lottoListKeys`)으로 작성한 걸 확인, 단수형(`lottoListKey`)으로 수정
ㄴ 의미를 고려하고 싶으면 단수복수가 문제가 아니라 `Key` → `Value`가 문제였다는 걸 깨달았지만 이 분량을 덮어쓰는 3번째 버전을 push한 뒤였기 때문에 pr로 메모만 따로 남깁니다...
1번째 작업 당시 오해 ~~(이전 딕셔너리 실행이력도 누적해야 되는 줄 알았던 것)~~ 때문에 공부하던 중, 
> "**딕셔너리에는 키에 해당하는 값을 위한** …딕셔너리 타입에는 Swift 4.0부터 …
=> Week2 [Step 3] Junely

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/Step2.swift, CodeStarterCamp_Week2/main.swift
@siwonkim0 
둘째 주 STEP 2 PR 입니다.
네이밍이 제일 어렵네요. 말씀대로 동사로 시작하는 makeLottoNumbers 을 함수명으로 했습니다.
makeLottoNumbers 함수는 STEP 1 순서도 대로 구현했습니다.
두 LottoNumber를 인자로 받아서 비교하는 compareTwoLottoNumbers 함수를 만들었습니다.
Set 타입의 교집합을 구해서 겹치는 번호가 있는지 확인했습니다.
isEmpty로 겹치는 번호가 있는지 판단하고, 있으면 겹치는 번호를 ", "로 구분해서 출력하도록 했습니다.
PR 메시지를 쓰다 보니 print 함수에서 separator는 기본 값으로 두고, 앞뒤 공백을 없애면 된다는 걸 발견했네요. 집에 가는 대로 수정하겠습니다.
=> Week2 [STEP 2] 이준호

CodeStarterCamp_Week2/main.swift
@horeng2 
STEP2 PR입니다! 이번 미션부터 코드 작성도 더 많은 생각을 요구하게 되는 것 같아요! 막히는 부분도 조금씩 생기고 있습니다 😅
- 당첨 번호와 나의 번호를 어떻게 비교할 수 있을지 고민해 보았습니다.
- winningLottoNumber와 myLottoNumber가 둘 다 정수형 배열이기 때문에, 중첩 반복문을 통해서 비교하도록 했습니다.
- 당첨 번호와 나의 번호를 비교하교 출력하는 구문은 다음과 같았습니다.
> 축하합니다! 겹치는 번호는 1, 2, 3, 4, 5, 6 입니다!
- 하지만 제가 구현한 코드의 출력은 다음과 같습니다.
> 축하합니다! 겹치는 번호는 [1, 2, 3, 4, 5, 6] 입니다!
- 따라서 STEP2 에서 요구한대로 출력이 되고 있지 않은 상황이었습니다.
- 어떻게 하면 배열을 문자열로 출력할 수 있을지에 대한 방법을 찾아보다가, .joined() 메서드를 알게 되었습니다.
- .joined(separator: ", ") 메서드를 이용하면, 주어진 미션의 출력 결과와 동일하게 출력할 수 있음을 확인했습니다, 야호!🤩
- 이번 STEP 역시 해결이 되지 않은 점은 없었습니다.
- 지난번 STEP1 merge때 당첨번호를 저장하기 위한 컬렉션 타입으로 배열을 고른 것에 대한 이유를 피드백으로 받았었는데, 이에 대해서는 다음과 같은 답변을 드리고 싶습니다.
1. 딕셔너리의 경우 당첨번호를 Key : Value 쌍의 데이터 저장 방식을 사용할 필요가 없기 때문에 제외했습니다.
2. 집합의 경우 중복되지 않는 유일한 멤버만을 담고 있기 때문에 6개의 당첨번호를 …
=> Week2 [STEP2] codesparrow

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/function.swift, CodeStarterCamp_Week2/main.swift
@yeahg-dev
주어진 요구사항에 충실하게 하기 위해 노력해보았습니다!
- 이번 과제에서는 각각의 기능들을 함수로 구현해 보고자 노력하였습니다.
---
- 이번 과제에서는 막히는 부분은 없었습니다☺️
---
- 구현하던중 딕셔너리를 정렬해보고싶어서 dictonary.sorted{$0.0<$1.0} 이런식으로 구현해보았는데 아직 $0의 의미를 명확하게 파악하지 못한것같습니다.
- 제가 구글링하면서 이해한 바로는 dictionary 일 경우 `$0`이 첫번째 요소, `$0.0`은 첫번째 요소의 key값, `$0.1`은 value 값으로 이해했는데 혹시 정확하게 이해한 것이 맞을까요..?😂
=> WEEK2 [STEP3] 제리

CodeStarterCamp_Week2/main.swift
@July911 
- 회차와 당첨번호를 넣을 딕셔너리와 회차 입력에 필요한 변수 두 개를 추가했습니다. 함수 내부에서는 회차에 해당하는 변수를 +1 해주기만 할것이기 때문에 변수는 함수 밖으로 뺐습니다.
- 기존 당첨번호 생성 함수에서 딕셔너리추가와 회차 +1 코드 두 줄만 추가했습니다.
- 원하는 회차(Int)를 입력하면 회차와 당첨번호가 print되는 함수를 생성하고자 했습니다.
- 매개변수로 round, return값은 없이 print문으로 마무리했습니다.
- 딕셔너리는 키에 해당하는 값이 존재하는지 알 수 없기 때문에 optional binding이 필요합니다.
- if let을 사용해 안전하게 unwrapping을 시도했습니다.
```
=> Week2 [STEP3] 애종

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/main.swift, CodeStarterCamp_Week2/step2.swift
@gogosilver 
step2 PR입니다! 
> 미션지에서 1~45 사이의 랜덤숫자를 발행하라했을때 순간적으로 화면속야곰님이 말씀하신것중에 "Math를 이용해서..어쩌구"하는 말이 떠올랐습니다 그래서 아 이거구나! 하고 인터넷에 쳐봤더니 이게 웬걸 그저 Int.random하면 되는 일이었습니다. 아직은 써먹을때가 아니군요 ㅠ.ㅠ 이번 스탭도 무난하게 지나갈것같습니다!
> 코드를 작성하고 출력문을보려고 커맨드+R 할때 갑자기 맨왼쪽에 첨보는 창도 뜨고 
출력이 안되는겁니다.. 그래서 무시하고 다시 커맨드 +R 했는데 instance를 replace해서 쓸건지 add해서 쓸건지 물어보는 창이 나왔는데 add를 누르면 왠지 코드가 돌아가는프로세서가 관련된것 같아서 함부로 add했다간 컴퓨터가 아야할것같아 replace를 눌렀는데 다시 아까의 반복이었습니다.  
(사진으로 남겻으면 좋을텐데 찍어놓은게 없어서 죄송합니다..)
그러다가 어느 코드에 노랑색꼬리표가 달려있었는데 그걸 클릭했더니 
포인트브레이크엿나? 무슨브레이크가 뜨길래 아 여기서걸리는거구나 하고 
해당 코드를 지우고 다시 그대로 복붙해서 커맨드+R 했는데 실행이 된겁니다(엥?)
왜그런지 모르겠는데 혹시 아시는것이 있나해서 여쭤봅니다.
=> Week2 [STEP2] LimKIWoong

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/main.swift, CodeStarterCamp_Week2/step3.swift
@horeng2
안녕하세요! STEP 3 보내드립니다.
STEP 2에서 사용했던 `generateLottoNumber`함수를  재활용해서 Dictionary에 회차와 함께 저장하고 sort된 array를 리턴하여 출력하도록 구성하였습니다
- 옵셔널 사용이 아직 어려워요ㅠㅠ
- 함수 호출 시 `argument label`을 사용해 보았는데 언제나 네이밍에 대한 고밍을 하게 되네요
- 해결이 되지 않은 점은 없습니다.
- 원래는 회차 정보를 받아서 딕셔너리를 검색하고 해당되는 회차의 value까지 출력하도록 함수를 구성하였다가 나중에는 2개의 함수로 분리하였는데 그렇게 하면서 전역변수를 선언하여 사용했습니다. 전역변수 사용 시 피해야 할 점이나 주의해야 할 점이 혹시 있을까요?
주말 잘 보내시고 Week 3에서 만나요!
=> Week2 [STEP 3] 메네

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/main.swift, CodeStarterCamp_Week2/step2.swift, CodeStarterCamp_Week2/step3.swift
@siwonkim0 
- 예제에서  --회차를 키값으로 사용할때 Int형이 아닌 String으로 사용해서 현재 회차가 몇 회차인지 어떻게 알아야 하는지 고민했습니다.
-> 딕셔너리 요소를 카운팅 하는 방법으로 구현해 보았습니다.
이번주에 휴가를 다녀와서 진도를 잘 따라잡을 수 있을지 고민했었는데, 휴가 이후에 나름 열심히 해서 step 3 까지 올 수 있어서 기쁩니다ㅎㅎ🙌🏻
늘 꼼꼼한 코멘트 감사드리고, 좋은 주말 보내세요☺️🍀
=> Week3 [Step 3] seoyounghan

CodeStarterCamp_Week2/main.swift
@horeng2 
STEP3 PR입니다! 점점 미션이 어려워지고 복잡해져서 해결과정이 바로 떠오르지 않는 것 같아요 😵‍💫
그래도 열심히 고민하고 수정한 끝에 제가 원하는 결과가 나오는 것 만큼 행복한 일은 없는 것 같습니다 😎
이번에는 새로운 내용도 구현해 보았습니다!
---
**saveWinningLotto**
- 이번 STEP에서는 딕셔너리에 회차와 로또 번호를 Key : Value 쌍으로 저장해야 했습니다.
- 처음에는 saveWinningLotto 메서드에 이 회차와 번호 정보를 저장할 winningLottoHistory 딕셔너리를 전달인자로 주고 사용하려고 했지만, 컴파일 에러가 발생해 원인을 찾아 보았습니다.
> Input arguments to functions are immutable inside the function body and a Dictionary is a value type, so the dict you see inside the function is actually a copy of the original dictAges. When you call a function with a value type as its input argument, that input argument is passed by value, not passed by reference, hence inside the function you cannot access the original variable.
> …
=> Week2 [STEP3] codesparrow

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/Step3.swift, CodeStarterCamp_Week2/main.swift
@siwonkim0 
둘째 주 세 번째 PR입니다.
이번에도 네이밍이 제일 문제네요. 최대한 구체적인 이름으로 만들려고 했습니다.
만든 로또 번호를 담아둘 딕셔너리 makedLottoNumbers를 만들었습니다. 
lottoNumbersDict 이라는 타입 별칭을 만들어 사용했습니다.
addLottoNumbersToDictionary 함수에서 로또 번호를 로또 번호를 담을 딕셔너리를 인자로 받아서, 딕셔너리에 로또 번호를 추가합니다.
딕셔너리 count를 기준으로 1회차부터 순서대로 로또 번호를 추가하도록 했습니다.
전달 인자로 받은 딕셔너리의 값을 변경해야하기 때문에 입출력 매개변수를 사용했습니다.
printLottoNumbersInDictionary 함수는 회차 번호와 로또 번호를 담은 딕셔너리를 인자로 받아서, 해당 회차의 로또 번호를 출력합니다.
옵셔널 바인딩을 사용해서 출력할 회차의 로또 번호를 추출해서 출력합니다.
=> Week2 [STEP 3] 이준호

CodeStarterCamp_Week2/main.swift
@eunseo5355 
- 지난도 흐름도를 기반으로 코드를 작성해보며 새로운 method를 사용하게 되었습니다.
- 1~45의 숫자 범위를 지정하고 랜덤한 숫자를 생성하는 과정에서 random을 사용하게 되었습니다.
- 숫자 중복을 피하기 위해 컬렉션 중 set 타입을 사용하게 되었습니다.
- 또한 for_in 구문을 사용하려고 했는데, for _ in 1...6 을 하게 되면 숫자를 6번 뽑기는 하나, 그 중에 중복이 될 경우에는 set이 숫자를 버리게 되어버리고 그 자리는 비게 되므로 원하는 6개의 숫자가 나오지 않게 된다고 판단하게 되었습니다. while문에서 count를 이용해 숫자가 6개 전까지는 뽑는 행위가 계속 될 수 있도록 하였습니다.
🤔 한국말 문장으로는 간단하게 보였는데, '나의 로또 번호를 생성하기' 까지 정말 많은 고민과 시간을 필요로 했습니다. 
그래도 새롭게 적용해본 개념들이 많아 흥미가 있었고, 계속해서 개념을 익히고 적용하는 과정에 있는 것 같습니다.
- 이 과정에서는 위에서 나의 로또 번호 생성하는 과정과 동일하게 적용하여 해결하게 되었습니다.
- 컬렉션 set을 배우며 알게된 '교집합' 을 이용해 보면 어떨까 생각해서, 교집합 구문을 작성하게 되었습니다.
- 그리고 if else 조건문을 이용해, '교집합이 있을 경우 - A문구 출력 / 그 외의 경우 - B문구 출력'을 만들고 싶어 코드를 작성하는 과정에서 if 조건문에는 Bool 값이 들어가야 함을 알고 어떻게 표현하면 좋을 지 고민하게 되었고, '교집합 된 숫자가 1개라도 있으면 즉, 0개 이상이면' 이라고 지정해주고자, …
=> WEEK2 [STEP 2] chacha

CodeStarterCamp_Week2/STEP3.swift, CodeStarterCamp_Week2/main.swift
@LeeSungNo-ian `이안`님 STEP3 PR 드립니다.
처음에는 진짜 엄두도 안나던 과제를 제출까지 하게되어서 나름 뿌듯하기도 하고, 제가 재능이 없나 자책도 했던 시간이었습니다..
아직 많이 부족한 코드 같지만 리뷰 주시면 더 맞게 수정해보겠습니다.
---
- 옵셔널이 아직 어렵네요.. 딕셔너리는 실행시점에 해당 키의 벨류가 있는지 없는지 확신 할 수 없으니 옵셔널바인딩을 해주면 되는걸로 이해했습니다. 제가 `?`를 쓰지 않았는데 맞는 방법으로 진행 한건지 궁금했습니다.
---
- 함수네이밍은 길더라도 의미가 전달이 더 명확한게 좋을까요? 아니면 간략하지만 포인트만을 전달해주는게 더 좋을까요? 함수가 많아지고 계속 변수가 생기다보니 많이 복잡해져서 궁금했습니다.
=> Week2 [STEP3] gye0rehan

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/main.swift, CodeStarterCamp_Week2/makeLottoNum.swift, CodeStarterCamp_Week2/makeRounds.swift, CodeStarterCamp_Week2/selectRoundPrint.swift
@yeahg-dev 
joined메서드를 사용하기위해 [Int]Array를 [String]Array로 형변환하는 방법을 고민해 보았습니다. 
첫 번째는 map이라는 고차함수를 사용하는 것..! 
두번 째는 새로운 [String]Array를 만들어 Element하나 씩 String으로 캐스팅하여 넣기.
map함수를 사용하기엔 아직 부족한 것 같아 조금더 공부하고 사용해 보아야 겠어요.
* contains함수도 배열원소를 순환한다면, n^2로 시간복잡도가 똑같을 것 같아요!
=> Week2 [STEP3] SierraJY

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/File.swift, CodeStarterCamp_Week2/main.swift
@siwonkim0
내 로또 번호와 로또 당첨 번호를 겹치는 숫자를 확인하는 함수를 만들 때에 집합 연산을 통해 겹치는 번호를 구했는데 집합 연산은 Set 컬렉션 끼리만 사용할 수 있는 줄 알았지만 혹시나 하고 해보았는데 되어서 신기했습니다.
위에서 고민한 부분을 스위프트 언어 가이드에서 찾아보았지만 없어서 구글링을 했습니다만..
https://developer.apple.com/search/?q=intersection(_:)
이런 식으로 많은 것중에 어느 것을 참고하는게 좋을지 모르겠습니다.
=> Week2 [STEP 2] yonggipo

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/CheckLottoNumber.swift, CodeStarterCamp_Week2/main.swift
FlowChart를 그려보고 코드를 작성해보니 확실히 도움이 되는 것 같습니다
___
1. 출력할 때 [ ] 대괄호를 지우는 것을 많이 고민해봤는데 기존 데이터를 변형할 수 있게 해주는 map을 사용해서 String으로 바꾸고 
separator를 사용해봤습니다.
@keeplo
=> Week2 [STEP 2] 98-LEE

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/main.swift, CodeStarterCamp_Week2/step2-2.swift, CodeStarterCamp_Week2/step2.swift, CodeStarterCamp_Week2/step3.swift, step2-2.swift, step2.swift, step3.swift
@jsim27 
step2 pr입니다!
원하는대로 겹치는 값과 겹치는 값이 출력되지않았을때를 if문을 활용해서 작성했으나
"축하합니다 겹치는 번호는 [a,b,c] 입니다 "식의 대괄호가 덮어진 배열식으로 출력되어
대괄호를 벗겨내는 작업에서 많이 고민했습니다!
=> Week2 [STEP2] jonghwan

CodeStarterCamp_Week2/main.swift
@eunseo5355
헤일리! 드디어 week2 마지막 스텝이네요
항상 좋은 피드백 감사합니다 🙌
- 다른 분들의 PR과 피드백을 둘러보면서 '전역 변수와 함수를 배치하는 위치도 기준이 있어야 한다.'는 내용을 보았습니다. 원래는 코드의 흐름이나 미션의 todo리스트의 순서를 기준으로 배치하였었는데, 이번에는 변수는 변수끼리, 함수는 함수끼리 모아서 작성해봤습니다. 혹시 제가 방향성을 잘못 잡은거라면 이 부분에 대해서 피드백 해주셨으면 좋겠어요!
- 처음에 '새로운 로또 당첨 번호를 생성하면, 직전 회차에 1을 더해 금번 회차를 만들어냅니다.' 문장을, 변수 값의 변경이 감지되면 자동으로 실행되는 함수를 생성하라는 말인 줄 알고 찾아봤습니다. 프로퍼티 감시자처럼 말이죠! 구글링을 잠깐 해봤는데 전역 변수에 대한 옵저버는 찾기 쉽지 않더라고요. 그런데 2주차 과제라기엔 너무 어렵지않나 싶어서 다른 분들께 물어보니 그게 아니었습니다...
---
- 코드를 작성하고 배치하는데 있어서 좋은 방법이나 규칙이 있는지 알고싶어요!
=> Week2 [STEP 3] Gundy

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/main.swift, CodeStarterCamp_Week2/step3.swift
@July911 
- 아직 함수를 자유자재로 쓰는 것이 힘들어서 시행착오를 겪었던 것 같습니다. 
로또 당첨번호 생성 함수를 호출할 때마다 회차와 로또 번호를 dictionary에 저장하는 부분에서 우선 고민을 했습니다. 문제에서 로또 당첨 번호를 5번 생성하라 했으니 for in을 5번 쓰면 되겠다고 생각했지만 5번이 아닌 10번 20번 혹은 그 이상에도 적용될 수 있도록 함수에서 매개변수로 생성횟수를 두는 것이 좋을 것 같다는 생각을 했습니다. 함수를 만들 때 고려할 것으로 무엇을 입력값으로 받을 것인지 정하는 것이 중요하다는 것을 깨달았습니다. 또한 컬렉션 타입에 값들을 대입하려 한다면 전역변수로서 미리 저장해놓는 것이 가시적으로 편하다는 깨달음을 얻었습니다.
- dictionary에 저장된 로또 당첨 번호를 확인하기 위해 이것을 따로 함수로 만드는 것이 좋겠다는 생각을 했습니다. 원하는 회차의 로또 당첨 번호를 확인하기 위한 함수이기에 몇회차인지를 입력값으로 받는 것이 우선 맞다고 생각했습니다. 
몇회차인지를 입력값으로 받고 해당되는 로또 당첨 번호를 print문으로 출력하기 
위해 출력값인 [Int]를 상수에 저장해놓는 것이 좋다고 생각해서 
let lottonumbers: [Int] = saveLottoRecord["\(round)회차"]으로
놓았는데 자꾸 오류가 발생했습니다. 생각해보니 예를 들어 회차는 5회차까지
진행됐는데 7회차의 번호를 찾으려 한다면 오류가 발생합니다. 만약 optional
binding을 이용하지 않는다면 오류가 발생할 가능성을 차단하지 못하겠다는
생각이 들었습니다. …
=> Week2 [Step3} 상수동남자

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/WEEK2 STEP2.swift, CodeStarterCamp_Week2/main.swift
25줄 print부분에서 \(RandomNumbers)을 넣었더니 해당 배열의 대괄호가 같이 출력되었습니다. 대괄호 부분을 삭제할려고 지난 강의를 듣고 정리한 자료를 찾아보았습니다. separator을 사용하여 삭제할려고 했지만 먹히지 않았습니다. 배우지 않은 내용이지만 구글링을 통해서 .trimmingCharacters을 사용을 하면 삭제할 수 있어서 추가하여 넣었습니다.
=> Week2 [STEP 2] 남준

CodeStarterCamp_Week2/main.swift
@jsim27 안녕하세요 ! 오늘도 피드백 해주셔서 감사합니다 ☺️
step1에서는 최종목표가 Array, 즉 순서가 중요시되는 컬렉션을 구현하는게 맞다고 생각했지만
step2에서 순서를 고려하지 않는다는 부분을 보고 형변환을 하지않고 Set에서 해결하는게 맞다고 생각이 들어 
Set으로 해결했습니다. 당첨번호와 제 번호간 중복 번호는 반복문을 활용하지 않고 집합연산에 유리한 Set의 특성을 고려해서 교집합 intersection 함수를 이용했고요.
Q. 이게 제가 생각할 수있는 효율적인 함수라고 생각하는데 더 좋은 방법이 존재할까요? 
Q. 또 나무님의 관점에서 볼 때, 효율적인 코드는 어떤 코드일때 말하는 걸까요? (다양한 상황이 있으니까 특정하기 힘드실 건데 저는 그에 대한 관점이 조금 부족한 거같아서요,,)
---
**<요구하는 출력>**
**<내가 한 출력>**
출력을 해보면 [1,2] 등 이렇게 배열단위로 출력이 되는데 1,2 이런식으로 구현하려면 하나하나 지칭해서 출력해야합니다. 
하지만 Set을 하나하나 지칭해서 출력하려하면 Set은 수의 모임에 순서가 존재하지 않기때문에 개별 출력이 불가능하고, 
이에따라 Array로의 형변환이 이루어지지 않는 이상 해결할 수없는 문제라고 생각합니다. 여기에 대해서 어떻게 생각하세요?
=> Week2 [STEP2] Hwieee

CodeStarterCamp_Week2/main.swift
@eunseo5355 
이 부분에서 처음에는 스트링타입의 키와, 로또번호 숫자를 담기 위해 Int 타입의 값을 담고자 했습니다. 
```swift
var lottoNumberCollection : Dictionary<String,[Int]> = ["1회차": makeRandomLottoNumber()]
```
- 이렇게 코드를 구성했을 때, Step2 에서 기존에 만들었던 makeRandomLottoNumber()은 6개의 랜덤한 숫자를 뽑아 Set 타입에 넣어준 숫자배열이므로 왼쪽에도 Set타입의 정수배열이 필요함을 알게 되었습니다.
```swift
var lottoNumberCollection : Dictionary<String,Set<Int>> = ["x회차": makeRandomLottoNumber()]
```
- 딕셔너리에 저장하고자 하는 키와 값의 타입을 지정하고자 하는 키와 값의 타입과 동일하게 맞추어 주고 나서, 초기 값을 따로 넣지 않고 호출한 후에 키와 값을 저장해주어도 원활하게 실행되는 것을 알게되어 초기 값을 없애주었습니다. 
- 처음에는 lottoNumberCollection 을 5번 호출하고 원하는 키와 값을 각각 넣어주었다가, 일일이 키와 값을 쓰지 않고, "x회차", "x+1"회차 이런식으로 번거로움을 줄이기를 시도해보게 되었습니다.
```swift
var lottoNumberCollection : Dictionary<String,Set<Int>> = [ : ]
for x in 1...5 {
lottoNumberCollection["\(x)회차"] = …
```
=> Week2 [STEP3] chacha

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/LottoRoundMaker.swift, CodeStarterCamp_Week2/Step3.swift, CodeStarterCamp_Week2/main.swift
[ 회차 : 로또번호]를 저장하는 딕셔너리에서 로또번호를 정수형 array로 할지 문자열 array로 할지 고민을 했습니다.
처음엔 번호를 저장하기 때문에 자연스레 정수형으로 만들고 진행하였으나 마지막 결과를 출력할 때 [ ] 를 또 지워야 되는 문제가 생겼습니다.
그래서 딕셔너리의 로또번호 부분을 문자열로 수정하고 6개의 무작위 로또번호를 만드는 함수에서 .random을 string으로 감싸고 저장했습니다. 
이렇게 해서 저번 step처럼 따로 정수 -> 문자열로 바꾸는  map 없이
결과를 출력할 때 joined(separator : ) 메소드를 사용해서 [ ]를 지웠습니다.
___
func makeLottoNumber에서
실행을 여러번 해봤는데 정렬이 될때도 있고 안될때도 있습니다.  append가 맨 뒤에 붙여주는 거라서 그런 거 같다고 생각하는데
마지막에 return numberArray.sorted()를 하면 정렬이 되어야 하는 거 아닌가요
___
네이밍 관련해서 조언을 얻고 싶습니다.
깔끔하고 명확하게 알아볼 수 있는 이름을 지어보고 싶습니다.
아쉽거나 애매한 부분들 알려주시면 감사하겠습니다.
@keeplo
=> Week2 [STEP 3] 98-LEE

CodeStarterCamp_Week2/File.swift, CodeStarterCamp_Week2/main.swift
@siwonkim0
- 딕셔너리에서 로또 번호를 값으로 넣어줄려고 할려고 하니 기존 로또번호 생성을 세트 컬렉션으로 해서 가능할까.. 하고 고민을 많이 했습니다. 단순히 언어 가이드에서 공부한 것으로는 해결이 되지 않아서 구글링을 통해 혼합이 가능하다는 것을 보고 시도해보았습니다.
=> Week2 [STEP 3] yonggipo

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/main.swift, CodeStarterCamp_Week2/step2.swift, CodeStarterCamp_Week2/step3.swift
@jsim27  step3 pr보냈습니다!
회차가 더해진 딕셔너리를 출력하는 함수부분에서
딕셔너리 밸류값부분을 set로 출력되게했었는데
다시 -> 어레이배열 -> 문자열로 출력하는부분에서 좀 막혀있었습니다
회차를 더하는부분도 단순히 더하기함수로 만들어서 밖에꺼내와 반복문을 사용하는방법으로 진행했는데
비효율적인것같아서 고민하다 팀원의 도움을받아
함수내에서 매개변수와 반복문으로 자동으로 더해진 딕셔너리가 출력되게끔 진행했습니다
이번에 문제를 풀면서 매개변수와 함수를 활용하는게 정말 많이 부족하다는걸 느꼈습니다ㅎㅎ,,
제일어려운건 문제를 보고 크게 구조를 먼저 생각해내는게 제일어려운것같습니다
크게 구조가잡히면 어디서 어떤함수를 쓸것이고 결과값을 어떤식으로 출력해야겠다 이런게 생각날텐데 하는 생각이많이들었습니다ㅜ
=> Week2 [STEP3] jonghwan

CodeStarterCamp_Week2/main.swift
@wongbingg 
안녕하세요 웡빙! 
Step2 PR 보내드립니다. Step2 에서는 새롭게 배웠던 Set 컬렉션 타입을 직접 사용할 수 있어서 좋았던 것 같습니다.
다행히 큰 문제 없이 코드 작성할 수 있어서 너무너무 기분이 좋네요~!! 😄
- Set 콜렉션 타입의 편리한 점은 집합 연산이 가능하다는 것인데요, 미션을 수행하면서 myLottoNumbers는 상수를 선언할 때 이 녀석이 Set 타입이 맞나? 하는 의문이 들었습니다. Set 컬렉션타입을 선언하려면 오직 ```Set<Int> = [...]``` 밖에 없다고 생각했거든요!
```swift
let myLottoNumbers: [Int] = [1, 2, 3, 4, 5, 6]
``` 
- 제가 만들었던 순서도를 참고해서 함수를 만들어 갔습니다만... while 구문의 조건 작성할 때 조금 막혔답니다.
순서도에는 "Set Collection 멤버 수가 5보다 커질 때까지"라고 써놨기 때문입니다!
조건을 다시 이해해보고 아래와 같이 바꿔서 해결했습니다. 순서도에 "멤버 수가 6보다 작다면"으로 표현했다면 좋았겠네요.
```swift
while lottoNumbersSet.count < 6
```
- switch 구문도 공부했기 때문에 한 번 써먹어보고 싶었는데요! 사용하지 않기로 했습니다. 🥲
if-else 구문과 다르게 switch 구문은 비교값을 설정해서 각 케이스를 만들어야 했는데, 숫자 6개를 채우기 위해선 같은 작업을 하는 케이스를 5회 더 작성해야했기 때문입니다.
---
- Step3에서는 로또 번호를 생성할 때마다 Dictionary …
=> Week2 [STEP 2] Rowan

CodeStarterCamp_Week2/main.swift
@Judy-999 
안녕하세요 😄 
배우는게 점점 늘어날수록 어떤 곳에 어떻게 써야할 지 복잡해지고 있습니다.
---
예시 문구와 같이 결과를 출력할 때 배열의 멤버만 보여주고 싶은데 기본적으로 대괄호가 같이 출력되었습니다.
처음엔 `for-in` 문으로 멤버를 하나하나 반복시켜서 `print` 할 때 `terminator: ", "`로 붙여주었는데 마지막 번호 옆에도 `", "`가 계속 붙었습니다.
구글링 하면서 찾아본 결과 변수를 문자열 기준으로 나눈 뒤 붙여주는 `components`, `joined` 메서드가 있었습니다.
실행 결과 문장을 let 상수로 저장하고 상수에 있는 `[`, `]`를 제거하는 작업을 했습니다.
`components`를 사용하여 `[`, `]` 기준으로 나누어 문자열로 보여주고, 나눠진 요소들을`joined`로 합쳐주는 것으로 이해했습니다.
``` swift
let overlapNumber: String = "축하합니다! 겹치는 번호는 \(winLottoNumbers.intersection(myLottoNumbers).sorted()) 입니다!"
print(overlapNumber.components(separatedBy: ["[","]"]).joined())
```
=> Week2 [STEP 2] 혜모리

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/main.swift, CodeStarterCamp_Week2/step2.swift, CodeStarterCamp_Week2/step3.swift
@Judy-999
안녕하세요 쥬디! 낮에 도움주셔서 정말 감사했습니다. 
이번 미션은 정말 정말 어렵고 자신이 없었는데 많은 도움 부탁드리겠습니다. 😢 
---
저번 스텝 마지막에 추가 코멘트로 말씀해주신 부분이었는데, 해놓고도 코드가 깨끗해 보이지 않아 이게 아닌 것 같다는 생각이 들었습니다. 🥲
Step3에도 적용해야하는 부분이 있었습니다.
`if let`으로 배열을 옵셔널 바인딩한 후 `for-in`으로 배열을 나눴습니다.
혹시 `removeBracket` 함수를 `searchLottoNumbers` 함수 밖으로 꺼내는게 더 보기 좋을까요?
``` swift
func searchLottoNumbers(round: Int) {
let searchLottoList: Dictionary<String, Set<Int>> = saveLottoNumbers()
let lottoRound = "\(round)회차"
if let result = searchLottoList[lottoRound] {
let resultCount = result.count
func removeBracket(range: [Int] = Array(result).sorted(), count: Int = resultCount) {
for i in range {
if i != range[count - 1] {
print(i, terminator: ", ")
} else {
print(i, terminator: " ")
}
}
}
print("\(round)회차의 로또 당첨 번호는", terminator: " ")
removeBracket() …
```
=> Week2 [STEP 3] 혜모리

CodeStarterCamp_Week2/main.swift
@wongbingg 
안녕하세요 웡빙 👋
지난 STEP 2에서 많이 고민해보고 피드백 반영한 덕에 이번 스텝도 수월하게 결과 얻어낼 수 있었습니다.
정말 보람차고 기분이 좋네요~! 👍
이번 주 미션도 항상 도와주셔서 감사합니다😁
- Dictionary의 멤버를 추출하려면 옵셔널 바인딩이 불가피했습니다! 맨 처음 코드를 작성할 때, if-let 구문에서 Key에 회차를 직접 기입했는데 이렇게 되면 다음 회차의 번호를 구할 때 if let 구문 안쪽을 손봐야하는 부분이 마음에 들지 않았습니다.
- ```var wantedLottoRound```를 따로 선언하여 편하게 회차를 변경할 수 있도록 해결했습니다.
- 처음에는 ```var lottoRound = 0```을 ```saveLottoDataToDict``` 내부에 선언했습니다. 하지만 반복문을 사용해 로또 번호를 5회 생성 시, 매회 함수 내부에서 lottoRound가 0으로 초기화되기 때문에 함수 외부에 따로 선언했습니다.
- 영어 공부가 좀 더 필요한 것 같습니다.. 단번에 떠오르는 단어가 없어 몇 번씩 변수, 함수의 이름을 수정했어요. 😂
- ```wantedLottoRound``` 변수의 더 알아보기 좋은 이름이 생각나신다면 말씀 부탁드립니다!! (처음엔 findRound, findNumbersOfRound 등 여러가지 많이 써봤습니다 😅)
- 지난 회차에 그대로 가져다 쓸 수 있는 내용이 많아서 꽤나 빠르게 미션을 마무리한 느낌이 적지 않습니다ㅎㅎㅎ... 혹시 추가적으로 공부해야될 내용이나 수정하면 더 좋아질 부분이 보이신다면 코멘트 마구마구 …
=> WEEK2 [STEP 3] Rowan

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/Step2.swift, CodeStarterCamp_Week2/main.swift
@llingo 
링고! Step2입니다! 무난하게 작성한거 같긴한데 뭔가 복잡한 느낌이군요..🧐
PR을 보내기 전에 다른 분들은 어떻게 하셨나 봤었는데 intersection이라는 연산을 사용하는거 같더라구요 ㅠ intersection 대신 for문으로 작성했는데, 다음부터는 코드를 더 간결하게 작성할 수 있는 방법이 무엇이 있는지 찾아봐야겠어요!!
=> Week2 [Step2] 송중

CodeStarterCamp_Week2/main.swift
@llingo 
Step2 PR 올립니다!
- 이번 코드 작성에서는 랜덤 값 하나를 추출하여 insert 하는 방식을 활용하였는데 만약 여러개의 숫자를 한번에 뽑아아할 때는 어떻게 하는게 좋을지 잘 모르겠습니다.
- 겹치는 숫자 출력에 있어서 lottoResult 자체를 출력하려고 하다보니 []안에 포함된 형태로 출력 되어서 해당 부분을 빼내는데 고민을 많이 하였습니다. 새로운 방법은 없나 고민해 보았지만 현재 코드 방법 말고는 안떠올랐내요 ㅠ
- 집합 내에서 원소를 하나씩 빼내는 방법이 있는지 궁금합니다. 찾아본 바로는 forEach 같은 매서드들이 나오는데 원하는 것과 조금 다른 것 같습니다. 어떤 키워드로 공부를 하면 좋을지 추천해주시면 감사하겠습니다.
- 만약 일정 범위의 집합이나 배열에서 한번에 여러개의 숫자를 랜덤으로 뽑고 싶을 때는 어떤 매서드가 있을까요? 이 부분도 랜덤 함수 관련해서 찾아보았지만 하나만 출력 하는 경우가 나와서 관련 공부 키워드 알려주시면 공부해보겠습니다.
=> Week2 [STEP2] Noix

CodeStarterCamp_Week2/main.swift
@Groot-94 
두 번째 PR을 보냅니다 !
- String 타입이 아니었기에 어떻게 제거해야 할지 막막해서 이번에도 구글링을 통해 해결 방법을 찾아보았습니다.
- 검색 중 Joind과 map 메서드를 알게 되어 이 두 메서드를 활용해 괄호를 제거하였습니다.
- 괄호를 제거하는 코드도 함수로 따로 분리하는 것이 좋았을까요?
=> Week2 [STEP 2] 시월

CodeStarterCamp_Week2/main.swift
안녕하세요! Week2 [STEP 2] PR 드립니다.
고민했던 점
어떻게 랜덤한 숫자 6개를 뽑아낼까 고민을하였으며, 랜덤함수가 있다는 것은 알지만 조금 다른 방법으로 해보고 싶었습니다.
집합 컬렉션이 고유의 값과 순서가 뒤죽박죽인 성질을 이용해서 랜덤한 숫자를 형성할 수 있도록 하였습니다.
지난 번에 피드백 해주셨을 때 집합에서 subscript 반환이 안된다고 하셨는데... subscript가 뭔지 모르지만,
.popFirst() 메서드를 활용해서 처리를 해주었습니다.
또한 .popFirst()를 하여도 반복문이 다시 실행되었을 때 같은 값이 1번째 위치에 자리할 수 있어서,
중복값 방지를 위해 .remove()로 선택된 값을 집합 컬렉션에서 삭제해주었습니다.
해결이 되지 않은 점
subscript가 무엇인가?
조언을 얻고 싶은 부분
조금 색다르게 하고 싶어서 집합 컬렉션을 통해 문제를 해결하였는데, 아무래도 반복문을 45번 돌리면서 값을 넣어주고,
또 값을 45개를 다 형성하기 때문에 메모리 공간을 많이 차지하게 될 우려가 있는데,
제가 문제를 해결한 방법과 랜덤함수 둘 중에 어떤 것이 더 가벼울까요? 🤔
감사합니다. 좋은 하루 되세요!
@wongbingg
=> Week2 [STEP 2] Harry 

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/Step2.swift, CodeStarterCamp_Week2/Step3.swift, CodeStarterCamp_Week2/main.swift
@llingo 
안녕하세요! 링고! 
항상 세세한 피드백에 감사드려요!
Step3입니다!🔥
- 제대로 알기 위해 Declation부분을 확인했습니다. 반환값이 String이군요!
일반적으로 array를 프린트하면 "[1, 2, 3, 4]" 이런 형식으로 나오는데, joined separator의 반환값이 String이여서 "1, 2, 3, 4"로 나오는 것을 확인할 수 있었습니다.
- 정확한 Declation을 알고 사용하는 것이 효율적일거 같다고 느꼈어요!
- 이번 Step3에는 추가하지 않은 부분이지만 사용 가능합니다. 위에 Declation을 보면 매개변수의 타입이 String인것을 확인할 수 있습니다. lottoSet의 타입이 Int이기 때문에 Int를 String으로 바꿔주면 사용이 가능합니다.
- 사용할 수 있는지 확인한 결과입니다.
=> Week2 [Step3] 송중

CodeStarterCamp_Week2/main.swift
@llingo  
드디어 이주차 두번째 PR을 보내내요 좀 뒤쳐지는 거 같아 더 열심히 해야겠다고 다집합니다! 😳
- 랜덤 숫자를 어떻게 만들어야하지? 고민했지만 모르겠어서 구글링했습니다.
- myLottoNumbers나 lottoNumbes 변수로 지정할 때 변수? 상수? 무엇으로 지정할 지 고민하였습니다.
- 조건문의 경우 repeat-while 문을 사용해 보았는데 while을 사용해도 상관없어 보였습니다.
=> week2 [Step2] Owen

CodeStarterCamp_Week2/main.swift
@wongbingg 
웡빙! 주말은 잘 지내셨나요? 벌써 11월달입니다👏☺️
저번주에 일이 많아서 과제수행이 늦은감이 없지않아 있네요!
이번달도 활기차게보내셔요!
- STEP3 진행중 로또당첨번호 출력이 optional[~]로 되어서 어떻게 해야할까 고민을 하게됐습니다.
- STEP2에서 사용한 것 처럼 String으로 변환하여 array에 저장하는 방법도 고민해봤지만, 한번에 출력하는 함수가 훨씬 깔끔해 보여서 타캠퍼님들의 과제를 참조하여 구현했습니다!
---
- STEP2에서 '로또당첨 번호를 생성하는 함수'를 만들지않고 진행해버린바람에 STEP3초반부터 문제를 겪었습니다🥲
- 로또번호를 생성하는 함수를 만들어 진행하고있는데, 반복문을 돌려도 같은값만 출력하는 코드가 짜여졌어요!
- 예를들어 1회차~5회차 모두가 값이 1, 2, 3, 4, 5, 6 으로 같은 값이 출력되었답니다...!
- 원인은 로또 생성함수 밖에서 선언한 변수가 문제였던것같습니다. 함수 안쪽에서 선언하니 오류가 사라졌어요. 
```swift
//수정 전
var lotto: Set<Int> = []
func makeLotto() -> Set<Int> {
while lotto.count < 6 {
let lottoNumber = Int.random(in: 1...45)
lotto.insert(lottoNumber)
}
return lotto
}
//수정 후
func makeLotto() -> Set<Int> {
var lotto: Set<Int> = []
while lotto.count < 6 {
let lottoNumber = …
```
=> Week2 [STEP 3] 무리

CodeStarterCamp_Week2/main.swift
@Groot-94
Week2 마지막 PR을 보냅니다 !
- `viewLottoRounds` 함수를 작성하는 과정에서 `Cannot find 'lottoDictionary' in scope` 오류를 보게 되었습니다.
- 구글과 다른 캠퍼분의 TIL을 읽어보다 저의 `lottoDictionary` 변수가 `saveLottoRounds` 내에서 작성되어 그렇다는 것을 깨닫고 오류를 수정하였습니다.
- 함수가 늘어날 수록 네이밍에 더더욱 고민이 되는 것 같아요,,ㅎ 저번 미션 보다 조금은 좋아졌길 바라는 마음으로 네이밍 했습니다😅
=> Week2 [STEP3] 시월

CodeStarterCamp_Week2/main.swift
안녕하세요. @wongbingg 
2주차 2번 과제를 PR 요청드립니다.
이번 과제에서 예시 출력 화면을 구현하기 위해 공백이나 쉼표의 출력 위치에 시행착오가 많이 필요했습니다.
=> Week2 [STEP 2] kokkile

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, Step3/main.swift
@wongbingg 
이번 미션을 수행하는데 가장 큰 어려움은 문제를 이해하는데 있었던 것 같습니다.
개념을 이해하고 그걸 응용시키는게 너무 어렵네요 😢 
dictionary 에 저장한다는 개념을 이해하기 어려웠던 것 같아요.
처음부터 감을 못잡아서 다른 캠퍼분들을 많이 참고했는데 dictionary 를 만들고 출력(?)하는게 없었습니다.
저는 5번 생성해야 한다고 해서 1회차 : 번호, 2회차: 번호 ..... 5회차: 번호 이렇게 값이 출력이 된 후에 거기서 원하는 회차를 찾는 그런식으로 문제를 이해했는데  dictionary  변수를 만들어서 옵셔널 바인딩으로 원하는 회차를 출력하도록 하는게 과제의 핵심이였다는 걸 뒤늦게 알게되었습니다. 이 문제는 dictionary와 optional 개념을 아직 잘 모른다는 뜻인거 같습니다 😢 
회차를 key, 생성번호를 value로 잡고 dictionary 변수를 만들었고
1회차 : 1, 2, 3, 4, 5, 6 을 표현하는 건 만들었는데 회차에 1을 더해 금번 회차를 만들어서 새로운 번호를 생성 하는 건 하지 못한것 같습니다.
직전회차와 금번회차를 각각 다른 매개변수로 잡고 해야할까요?
=> Week2 [STEP3] 졔

CodeStarterCamp_Week2/main.swift
안녕하세요. @wongbingg 
2주차 세 번째 과제를 PR 요청드립니다!
현재 코드에서는 파라미터를 `prevLottoDictionary`로, 리턴할 변수를 `nextLottoDictionary`로 분리하여 작성했습니다.
그 이유는 파라미터를 변경(회차 정보 추가)해서 리턴하려고 하니, 파라미터는 let값이라 변경이 불가능하다는 에러가 발생했기 때문입니다.
위 에러 관련하여 세가지 선택지가 있었습니다.
(1) 파라미터를 함수 내에서 변경하는 방법을 찾기
(2) 파라미터를 받지 않고, 함수 리턴도 하지 않고, 딕셔너리 전역변수를 함수 내에서 변경
(3) 현재 코드처럼 파라미터와 리턴할 변수를 분리하여 작성
(1), (2)번의 방법처럼 함수 외부의 데이터를 직접 수정하는것은 객체지향 프로그래밍에서 지양하는 방법이라는 의견이 있어서(의도치 않은 사이드 이펙트 때문에?), (3)번으로 구현해보았습니다.
=> Week2 [STEP 3] kokkile

CodeStarterCamp_Week2/main.swift
안녕하세요~
⭐️고민했던 점
1. 기존 Set 컬렉션으로 랜덤 6개의 숫자를 형성하는 것이... 함수 호출을 5번 동시에 하니 같은 값이 출력되는 경우가 있어서 랜덤 값이 제대로 형성이 되지 않아서 배열을 shuffle() 메서드를 통해 랜덤 값을 형성하도록 변경하였습니다. 
2. countHistory 변수를 통해 로또 당첨 번호 함수가 호출될 때 마다 카운트가 +1 되록하여 회차 관리를 하였는데, 로또 당첨 번호 생성 함수 내부의 배열을 초기화하지 않으니 값이 1회차, 1회차 + 2회차, 1회차 + 2회차 + 3회차 이런 식으로 누적이되어서 removeAll()을 통해 딕셔너리 컬렉션에 값을 넣어주면 배열은 값을 모두 제거하도록 하였습니다. 
3. 문제에서는 print된 문구가 2회차 당첨 값은 1, 2, 3, 4, 5 ,6입니다. 로 출력되는데 배열을 넣어서 출력하면 2회차 당첨 값은 [1, 2, 3, 4, 5, 6]입니다. 이렇게 중괄호가 같이 나와서... 나름 자체적으로 문제 출력과 같게 맞춰줬습니다. 
⭐️해결이 되지 않은 점
1. 왜 Set을 통해 컬렉션을 만들고 함수를 통해 여러번 호출했을 때 같은 값을 지니는 컬렉션이 형성되는 경우가 생겼던걸까요? 
⭐️조언을 얻고 싶은 부분
1. 고민했던 점 3번을 제 코드와 같이 해줘야만 중괄호가 삭제되게 출력되는지가 궁금해요. 
감사합니다~ @wongbingg
=> Week2 [STEP 3] Harry

CodeStarterCamp_Week2/main.swift
@Judy-999 
1. 출력에 많은 고민을 했습니다
반복문으로 출력을 해줬는데 "2, 3, 입니다!" 이렇게 마지막 숫자에 ","가 찍히는 경우가 존재해 if문을 이용해 마지막 번호일 경우 ","가 안찍히게 해줬습니다
2. 랜덤한 로또 숫자를 Set로 만들어줬기 때문에 교집합을 통해 맞는 숫자를 골라냈지만 마지막 숫자를 통해 ","를 없애는 출력법을 사용할 수 없어서 배열로 만들었습니다
1. 조금 더 출력을 간편하게 만들 수 있다고 생각하는데 그 부분에 대해서 해결이 되지 않습니다. print문에 배열을 넣었을 때 "[", "]"가 표시되지 않고 출력이 되는 방법이 있는지 조언을 얻고 싶습니다
=> Week2 [STEP2] 레옹아범

CodeStarterCamp_Week2/main.swift
**@Judy-999 언제나 감사합니다~~**
생각보다 막히게 되는 부분이 너무 많았어서, 한두시간이면 되겠지 한게 4시간이 지났네요 ㅠ
- Set과 Array가 intersection이 된다는 걸 몰라서 한가지로 변환해야 하나 고민했다가 해결
- 조건문에 대해 공부할때 이름이 멋있었던 guard를 써보려고 시도
- 당첨 검사를 할 때, intersection이 없으면 꽝이라는걸 표시하기 위해 "intersection이 nil 이면" 이라는 조건문을 옵셔널과 함께 작성하다가 계속 막혀서 연구.. (guard를 잘못 썼나 하고 계속 고민)
하다보니 intersection 해당되는게 없을때 nil이라고 에러가 나오지 않고 그냥 비어있는걸로 표시가 되어서, count 사용하는 해결방법 시도
- 당첨 번호의 앞 뒤 대괄호를 없애는 다양한 방법들에 대해 고민
1. overlappingNumbers.forEach{ print($0, terminator: ",") } 를 썼는데 마지막 번호 뒤에 콤마가 남는게 마음에 들지 않고, forEach와 클로져? 등 아직 잘 모르는 개념보다 이미 알고 있는걸로 해결하려고 함
2. 구글링하니 joined 라는 메소드를 사용할 수 있다고 나왔는데 어떻게 해도 계속 안됨.. (에러 메시지 : 'No exact matches in call to instance method 'joined'')
3. 결국 Int를 String으로 변환해서 작업하려는데 outputNumbers = String(overlapNumbers) 방식이 가능하다고 구글링으로 봤는데 안됨.. (에러 메시지 : 'No …
=> Week2 [STEP 2] Medi0202

CodeStarterCamp_Week2/main.swift
@Judy-999 
1. STEP3에 대해 이해가 잘 안됐습니다
당첨번호를 랜덤으로 만들고 특정 회차 당첨번호를 출력한다고 이해했는데 이게 맞을까요??
2. component, trimmingCharacters에 관한 질문입니다
```
func printRoundCorrectNumber(round: Int, numbers: Set<Int>) {
let lottoNumbers = "\(numbers.sorted())".trimmingCharacters(in: ["[", "]"])
print("\(round)회차의 당첨번호는 \(lottoNumbers) 입니다")
}
```
출력부분에 이렇게 작성했는데 numbers와 같은 Int배열일 경우 trimmingCharacters나 components가 사용이 안돼서 [components](https://developer.apple.com/documentation/foundation/nsstring/1413214-components), [trimmingCharacters](https://developer.apple.com/documentation/foundation/nsstring/1415462-trimmingcharacters) 의 항목에 String과 CharacterSet으로 되어있어서 위와 같이 String으로 만들어서 사용했는데 이렇게 사용하는게 맞는걸까요?
이 부분은 이전 스텝부터 여러가지 검색해서 찾아봤는데 
```
func printRoundCorrectNumber(round: Int, numbers: Set<Int>) {
}
```
이런 함수가 있다고 …
=> Week2 [STEP 3] 레옹아범

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/Step2.swift, CodeStarterCamp_Week2/main.swift
@Judy-999 
- 저번 피드백 말씀해주신데로 전역변수를 줄이려고 노력했습니다.
- 계속 벽에 막히던 부분이 로또 번호를 반복해서 생성해도 1회차~5회차 모두 같은 결과가 나오는거였는데요. (어제 그것때문에 포기하고 오늘 리트라이). 고민고민하다보니 로또 번호가 생성되서 luckyNumbers에 6개 꽉 차 있어서 더 못만드는것이었더군요. 그래서 로또 한세트 만들고 -> 딕셔너리에 저장하고 -> 내용물을 비우는 식으로 해결했습니다!
- 옵셔널 타입을 꺼내 쓰는걸 처음 해보니 막히는 곳이 많았어요. 저번에도 썼던 guard let 을 쓰고 뒤에 조건문을 달았는데 계속 에러가 나와서 교육자료를 다시 검토해보니, 조건문이 필요 없이 값이 있으면 true, nil이면 false 로 진행이 되는거였더군요.
- 옵셔널을 쓰려면 꼭 ?나 !를 써야 하나했는데, 제 결과물도 그렇고 다른 사람들도 안쓰고 잘 해결된거 같아서 약간 혼란스러워요.
- 피드백 하나하나가 피가 되고 살이 됩니닷. 감사합니다 👍
=> Week2 [STEP 3] Medi0202

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/main.swift, CodeStarterCamp_Week2/week2_step2.swift, CodeStarterCamp_Week2/week2_step3.swift
@Judy-999 
Week2 [Step3] 과제입니다
항상 친철하고 좋은 답변 감사합니다 :)
=> Week2 [Step3] occasion

CodeStarterCamp_Week2/main.swift
@Judy-999 안녕하세요! 이번 STEP 2 미션 진행하면서 고민했던 점과 조언이 필요한 부분에 대해 공유드립니다 🙌
겹치는 번호를 콤마로 구분하여 출력하기 위해 `joined` 함수를 사용하려 했으나
해당 함수는 String 타입의 값만 처리가 가능하므로
Int 배열인 겹치는 번호를 String 배열로 변환하고자 하였습니다.
검색을 통해 `map`을 이용하면 정해진 기준에 따라 배열의 모든 항목을 변환하여 
반환해준다는 것을 알게 되었습니다.
검색 과정에서 제가 가장 먼저 접했던 코드는 `array.map{ String($0) }` 이었습니다.
`$0`의 의미가 무엇인지 찾아보다가 위 형태가 아래 코드를 매우 축약한 형태임을 알 수 있었습니다.
`array.map({ (value: Int) -> String in return String(value) })`
축약된 코드만 봤을 때는 map이 어떤 구조로 실행되는지 알기 어려웠는데
원래 형태를 보고 map에서 각 부분이 어떤 역할을 하는지 알게 되었습니다.
```swift
/* 원래 코드 */
var randomNumber = Int.random(in: 1...45)
/* 수정한 코드 */
let randomNumber = Int.random(in: 1...45)
```
원래는 `Int.random(in: 1...45)`의 값이 계속해서 랜덤으로 바뀌기 때문에
변수로 선언해야한다고 생각했는데 다음과 같은 경고가 발생했습니다.
`Variable 'randomNumber' was never mutated; consider changing to 'let' …
=> Week2 [STEP 2] 아샷추

CodeStarterCamp_Week2.xcodeproj/project.pbxproj, CodeStarterCamp_Week2/lottoRoundSearch.swift, CodeStarterCamp_Week2/main.swift
@jaemuYeo 잼킹! Step3 PR이에요!
- 먼저 각 회차별로 로또 당첨 번호를 저장하는 roundSave 딕셔너리 변수를 만들어 주었습니다.
- roundCount 변수는 현재 회차를 저장하는 변수이고 새로운 회차가 추가될 때마다 1씩 증가합니다.
- lottoRoundSave() 함수는 새로운 회차를 추가 후 번호를 생성하여 roundSave에 저장하는 함수입니다.
- getLottoRoundNumber() 함수는 특정 회차의 로또 번호를 옵셔널로 안전하게 가져오는 함수입니다. 존재하지 않는 회차를 가져올 시 nil을 반환합니다.
- printLottoRound() 함수는 특정 회차와 그 회차의 로또 번호를 출력하는 함수입니다. if let을 사용하여 옵셔널 바인딩을 해주었습니다.
- for 문을 사용하여 5회차까지 번호를 생성하여 lottoRoundSave() 함수를 통해 저장합니다.
- 그리고 printLottoRound() 함수를 사용하여 원하는 회차의 로또 번호를 출력합니다.
- 매번 새롭게 번호를 생성하면 같은 회차에 다른 번호가 들어갑니다.
- 따로 사용자 시스템에 로컬로 저장하는 방법을 사용하지 않고 구현하고 싶었습니다 ㅠ
=> [Round2] Step3 - joo
